exports.convertIOCCountryCode = function (IOCCountryCode) {

  switch (IOCCountryCode.toUpperCase()) {
    case 'AFG' : return { countryName: 'Afghanistan', FIFA: 'AFG', ISO3: 'AFG', ISO2: 'AF'}; break;
    case 'ALB' : return { countryName: 'Albania', FIFA: 'ALB', ISO3: 'ALB', ISO2: 'AL'}; break;
    case 'ALG' : return { countryName: 'Algeria', FIFA: 'ALG', ISO3: 'DZA', ISO2: 'DZ'}; break;
    case 'ASA' : return { countryName: 'American Samoa', FIFA: 'ASA', ISO3: 'ASM', ISO2: 'AS'}; break;
    case 'AND' : return { countryName: 'Andorra', FIFA: 'AND', ISO3: 'AND', ISO2: 'AD'}; break;
    case 'ANG' : return { countryName: 'Angola', FIFA: 'ANG', ISO3: 'AGO', ISO2: 'AO'}; break;
    case 'ATG' : return { countryName: 'Antigua and Barbuda', FIFA: 'ATG', ISO3: 'ATG', ISO2: 'AG'}; break;
    case 'ARG' : return { countryName: 'Argentina', FIFA: 'ARG', ISO3: 'ARG', ISO2: 'AR'}; break;
    case 'ARM' : return { countryName: 'Armenia', FIFA: 'ARM', ISO3: 'ARM', ISO2: 'AM'}; break;
    case 'ARU' : return { countryName: 'Aruba', FIFA: 'ARU', ISO3: 'ABW', ISO2: 'AW'}; break;
    case 'AUS' : return { countryName: 'Australia', FIFA: 'AUS', ISO3: 'AUS', ISO2: 'AU'}; break;
    case 'AUT' : return { countryName: 'Austria', FIFA: 'AUT', ISO3: 'AUT', ISO2: 'AT'}; break;
    case 'AZE' : return { countryName: 'Azerbaijan', FIFA: 'AZE', ISO3: 'AZE', ISO2: 'AZ'}; break;
    case 'BAH' : return { countryName: 'The Bahamas', FIFA: 'BAH', ISO3: 'BHS', ISO2: 'BS'}; break;
    case 'BHR' : return { countryName: 'Bahrain', FIFA: 'BHR', ISO3: 'BHR', ISO2: 'BH'}; break;
    case 'BAN' : return { countryName: 'Bangladesh', FIFA: 'BAN', ISO3: 'BGD', ISO2: 'BD'}; break;
    case 'BRB' : return { countryName: 'Barbados', FIFA: 'BRB', ISO3: 'BRB', ISO2: 'BB'}; break;
    case 'BLR' : return { countryName: 'Belarus', FIFA: 'BLR', ISO3: 'BLR', ISO2: 'BY'}; break;
    case 'BEL' : return { countryName: 'Belgium', FIFA: 'BEL', ISO3: 'BEL', ISO2: 'BE'}; break;
    case 'BLZ' : return { countryName: 'Belize', FIFA: 'BLZ', ISO3: 'BLZ', ISO2: 'BZ'}; break;
    case 'BEN' : return { countryName: 'Benin', FIFA: 'BEN', ISO3: 'BEN', ISO2: 'BJ'}; break;
    case 'BER' : return { countryName: 'Bermuda', FIFA: 'BER', ISO3: 'BMU', ISO2: 'BM'}; break;
    case 'BHU' : return { countryName: 'Bhutan', FIFA: 'BHU', ISO3: 'BTN', ISO2: 'BT'}; break;
    case 'BOL' : return { countryName: 'Bolivia', FIFA: 'BOL', ISO3: 'BOL', ISO2: 'BO'}; break;
    case 'BIH' : return { countryName: 'Bosnia and Herzegovina', FIFA: 'BIH', ISO3: 'BIH', ISO2: 'BA'}; break;
    case 'BOT' : return { countryName: 'Botswana', FIFA: 'BOT', ISO3: 'BWA', ISO2: 'BW'}; break;
    case 'BRA' : return { countryName: 'Brazil', FIFA: 'BRA', ISO3: 'BRA', ISO2: 'BR'}; break;
    case 'VGB' : return { countryName: 'British Virgin Islands', FIFA: 'VGB', ISO3: 'VGB', ISO2: 'VG'}; break;
    case 'BRU' : return { countryName: 'Brunei', FIFA: 'BRU', ISO3: 'BRN', ISO2: 'BN'}; break;
    case 'BUL' : return { countryName: 'Bulgaria', FIFA: 'BUL', ISO3: 'BGR', ISO2: 'BG'}; break;
    case 'BFA' : return { countryName: 'Burkina Faso', FIFA: 'BFA', ISO3: 'BFA', ISO2: 'BF'}; break;
    case 'BDI' : return { countryName: 'Burundi', FIFA: 'BDI', ISO3: 'BDI', ISO2: 'BI'}; break;
    case 'CAM' : return { countryName: 'Cambodia', FIFA: 'CAM', ISO3: 'KHM', ISO2: 'KH'}; break;
    case 'CMR' : return { countryName: 'Cameroon', FIFA: 'CMR', ISO3: 'CMR', ISO2: 'CM'}; break;
    case 'CAN' : return { countryName: 'Canada', FIFA: 'CAN', ISO3: 'CAN', ISO2: 'CA'}; break;
    case 'CPV' : return { countryName: 'Cape Verde', FIFA: 'CPV', ISO3: 'CPV', ISO2: 'CV'}; break;
    case 'CAY' : return { countryName: 'Cayman Islands', FIFA: 'CAY', ISO3: 'CYM', ISO2: 'KY'}; break;
    case 'CTA' : return { countryName: 'Central African Republic', FIFA: 'CTA', ISO3: 'CAF', ISO2: 'CF'}; break;
    case 'CHA' : return { countryName: 'Chad', FIFA: 'CHA', ISO3: 'TCD', ISO2: 'TD'}; break;
    case 'CHI' : return { countryName: 'Chile', FIFA: 'CHI', ISO3: 'CHL', ISO2: 'CL'}; break;
    case 'CHN' : return { countryName: 'China', FIFA: 'CHN', ISO3: 'CHN', ISO2: 'CN'}; break;
    case 'COL' : return { countryName: 'Colombia', FIFA: 'COL', ISO3: 'COL', ISO2: 'CO'}; break;
    case 'COM' : return { countryName: 'Comoros', FIFA: 'COM', ISO3: 'COM', ISO2: 'KM'}; break;
    case 'COD' : return { countryName: 'Democratic Republic of Congo', FIFA: 'COD', ISO3: 'COD', ISO2: 'CD'}; break;
    case 'CGO' : return { countryName: 'Republic of Congo', FIFA: 'CGO', ISO3: 'COG', ISO2: 'CG'}; break;
    case 'COK' : return { countryName: 'Cook Islands', FIFA: 'COK', ISO3: 'COK', ISO2: 'CK'}; break;
    case 'CRC' : return { countryName: 'Costa Rica', FIFA: 'CRC', ISO3: 'CRI', ISO2: 'CR'}; break;
    case 'CIV' : return { countryName: "Côte d'Ivoire", FIFA: 'CIV', ISO3: 'CIV', ISO2: 'CI'}; break;
    case 'CRO' : return { countryName: 'Croatia', FIFA: 'CRO', ISO3: 'HRV', ISO2: 'HR'}; break;
    case 'CUB' : return { countryName: 'Cuba', FIFA: 'CUB', ISO3: 'CUB', ISO2: 'CU'}; break;
    case 'CYP' : return { countryName: 'Cyprus', FIFA: 'CYP', ISO3: 'CYP', ISO2: 'CY'}; break;
    case 'CZE' : return { countryName: 'Czech Republic', FIFA: 'CZE', ISO3: 'CZE', ISO2: 'CZ'}; break;
    case 'DEN' : return { countryName: 'Denmark', FIFA: 'DEN', ISO3: 'DNK', ISO2: 'DK'}; break;
    case 'DJI' : return { countryName: 'Djibouti', FIFA: 'DJI', ISO3: 'DJI', ISO2: 'DJ'}; break;
    case 'DMA' : return { countryName: 'Dominica', FIFA: 'DMA', ISO3: 'DMA', ISO2: 'DM'}; break;
    case 'DOM' : return { countryName: 'Dominican Republic', FIFA: 'DOM', ISO3: 'DOM', ISO2: 'DO'}; break;
    case 'ECU' : return { countryName: 'Ecuador', FIFA: 'ECU', ISO3: 'ECU', ISO2: 'EC'}; break;
    case 'EGY' : return { countryName: 'Egypt', FIFA: 'EGY', ISO3: 'EGY', ISO2: 'EG'}; break;
    case 'SLV' : return { countryName: 'El Salvador', FIFA: 'SLV', ISO3: 'SLV', ISO2: 'SV'}; break;
    case 'EQG' : return { countryName: 'Equatorial Guinea', FIFA: 'EQG', ISO3: 'GNQ', ISO2: 'GQ'}; break;
    case 'ERI' : return { countryName: 'Eritrea', FIFA: 'ERI', ISO3: 'ERI', ISO2: 'ER'}; break;
    case 'EST' : return { countryName: 'Estonia', FIFA: 'EST', ISO3: 'EST', ISO2: 'EE'}; break;
    case 'ETH' : return { countryName: 'Ethiopia', FIFA: 'ETH', ISO3: 'ETH', ISO2: 'ET'}; break;
    case 'FIJ' : return { countryName: 'Fiji', FIFA: 'FIJ', ISO3: 'FJI', ISO2: 'FJ'}; break;
    case 'FIN' : return { countryName: 'Finland', FIFA: 'FIN', ISO3: 'FIN', ISO2: 'FI'}; break;
    case 'FRA' : return { countryName: 'France', FIFA: 'FRA', ISO3: 'FRA', ISO2: 'FR'}; break;
    case 'TAH' : return { countryName: 'French Polynesia', FIFA: 'TAH', ISO3: 'PYF', ISO2: 'PF'}; break;
    case 'GAB' : return { countryName: 'Gabon', FIFA: 'GAB', ISO3: 'GAB', ISO2: 'GA'}; break;
    case 'GAM' : return { countryName: 'The Gambia', FIFA: 'GAM', ISO3: 'GMB', ISO2: 'GM'}; break;
    case 'GEO' : return { countryName: 'Georgia', FIFA: 'GEO', ISO3: 'GEO', ISO2: 'GE'}; break;
    case 'GER' : return { countryName: 'Germany', FIFA: 'GER', ISO3: 'DEU', ISO2: 'DE'}; break;
    case 'GHA' : return { countryName: 'Ghana', FIFA: 'GHA', ISO3: 'GHA', ISO2: 'GH'}; break;
    case 'GRE' : return { countryName: 'Greece', FIFA: 'GRE', ISO3: 'GRC', ISO2: 'GR'}; break;
    case 'GRN' : return { countryName: 'Grenada', FIFA: 'GRN', ISO3: 'GRD', ISO2: 'GD'}; break;
    case 'GUM' : return { countryName: 'Guam', FIFA: 'GUM', ISO3: 'GUM', ISO2: 'GU'}; break;
    case 'GUA' : return { countryName: 'Guatemala', FIFA: 'GUA', ISO3: 'GTM', ISO2: 'GT'}; break;
    case 'GUI' : return { countryName: 'Guinea', FIFA: 'GUI', ISO3: 'GIN', ISO2: 'GN'}; break;
    case 'GNB' : return { countryName: 'Guinea-Bissau', FIFA: 'GNB', ISO3: 'GNB', ISO2: 'GW'}; break;
    case 'GUY' : return { countryName: 'Guyana', FIFA: 'GUY', ISO3: 'GUY', ISO2: 'GY'}; break;
    case 'HAI' : return { countryName: 'Haiti', FIFA: 'HAI', ISO3: 'HTI', ISO2: 'HT'}; break;
    case 'HON' : return { countryName: 'Honduras', FIFA: 'HON', ISO3: 'HND', ISO2: 'HN'}; break;
    case 'HKG' : return { countryName: 'Hong Kong', FIFA: 'HKG', ISO3: 'HKG', ISO2: 'HK'}; break;
    case 'HUN' : return { countryName: 'Hungary', FIFA: 'HUN', ISO3: 'HUN', ISO2: 'HU'}; break;
    case 'ISL' : return { countryName: 'Iceland', FIFA: 'ISL', ISO3: 'ISL', ISO2: 'IS'}; break;
    case 'IND' : return { countryName: 'India', FIFA: 'IND', ISO3: 'IND', ISO2: 'IN'}; break;
    case 'IDN' : return { countryName: 'Indonesia', FIFA: 'IDN', ISO3: 'IDN', ISO2: 'ID'}; break;
    case 'IRN' : return { countryName: 'Iran', FIFA: 'IRN', ISO3: 'IRN', ISO2: 'IR'}; break;
    case 'IRQ' : return { countryName: 'Iraq', FIFA: 'IRQ', ISO3: 'IRQ', ISO2: 'IQ'}; break;
    case 'IRL' : return { countryName: 'Ireland', FIFA: 'IRL', ISO3: 'IRL', ISO2: 'IE'}; break;
    case 'ISR' : return { countryName: 'Israel', FIFA: 'ISR', ISO3: 'ISR', ISO2: 'IL'}; break;
    case 'ITA' : return { countryName: 'Italy', FIFA: 'ITA', ISO3: 'ITA', ISO2: 'IT'}; break;
    case 'JAM' : return { countryName: 'Jamaica', FIFA: 'JAM', ISO3: 'JAM', ISO2: 'JM'}; break;
    case 'JPN' : return { countryName: 'Japan', FIFA: 'JPN', ISO3: 'JPN', ISO2: 'JP'}; break;
    case 'JOR' : return { countryName: 'Jordan', FIFA: 'JOR', ISO3: 'JOR', ISO2: 'JO'}; break;
    case 'KAZ' : return { countryName: 'Kazakhstan', FIFA: 'KAZ', ISO3: 'KAZ', ISO2: 'KZ'}; break;
    case 'KEN' : return { countryName: 'Kenya', FIFA: 'KEN', ISO3: 'KEN', ISO2: 'KE'}; break;
    case 'PRK' : return { countryName: 'North Korea', FIFA: 'PRK', ISO3: 'PRK', ISO2: 'KP'}; break;
    case 'KOR' : return { countryName: 'South Korea', FIFA: 'KOR', ISO3: 'KOR', ISO2: 'KR'}; break;
    case 'KUW' : return { countryName: 'Kuwait', FIFA: 'KUW', ISO3: 'KWT', ISO2: 'KW'}; break;
    case 'KGZ' : return { countryName: 'Kyrgyzstan', FIFA: 'KGZ', ISO3: 'KGZ', ISO2: 'KG'}; break;
    case 'LAO' : return { countryName: 'Laos', FIFA: 'LAO', ISO3: 'LAO', ISO2: 'LA'}; break;
    case 'LVA' : return { countryName: 'Latvia', FIFA: 'LVA', ISO3: 'LVA', ISO2: 'LV'}; break;
    case 'LBN' : return { countryName: 'Lebanon', FIFA: 'LBN', ISO3: 'LBN', ISO2: 'LB'}; break;
    case 'LES' : return { countryName: 'Lesotho', FIFA: 'LES', ISO3: 'LSO', ISO2: 'LS'}; break;
    case 'LBR' : return { countryName: 'Liberia', FIFA: 'LBR', ISO3: 'LBR', ISO2: 'LR'}; break;
    case 'LBY' : return { countryName: 'Libya', FIFA: 'LBY', ISO3: 'LBY', ISO2: 'LY'}; break;
    case 'LIE' : return { countryName: 'Liechtenstein', FIFA: 'LIE', ISO3: 'LIE', ISO2: 'LI'}; break;
    case 'LTU' : return { countryName: 'Lithuania', FIFA: 'LTU', ISO3: 'LTU', ISO2: 'LT'}; break;
    case 'LUX' : return { countryName: 'Luxembourg', FIFA: 'LUX', ISO3: 'LUX', ISO2: 'LU'}; break;
    case 'MKD' : return { countryName: 'Macedonia', FIFA: 'MKD', ISO3: 'MKD', ISO2: 'MK'}; break;
    case 'MAD' : return { countryName: 'Madagascar', FIFA: 'MAD', ISO3: 'MDG', ISO2: 'MG'}; break;
    case 'MWI' : return { countryName: 'Malawi', FIFA: 'MWI', ISO3: 'MWI', ISO2: 'MW'}; break;
    case 'MAS' : return { countryName: 'Malaysia', FIFA: 'MAS', ISO3: 'MYS', ISO2: 'MY'}; break;
    case 'MDV' : return { countryName: 'Maldives', FIFA: 'MDV', ISO3: 'MDV', ISO2: 'MV'}; break;
    case 'MLI' : return { countryName: 'Mali', FIFA: 'MLI', ISO3: 'MLI', ISO2: 'ML'}; break;
    case 'MLT' : return { countryName: 'Malta', FIFA: 'MLT', ISO3: 'MLT', ISO2: 'MT'}; break;
    case 'MTN' : return { countryName: 'Mauritania', FIFA: 'MTN', ISO3: 'MRT', ISO2: 'MR'}; break;
    case 'MRI' : return { countryName: 'Mauritius', FIFA: 'MRI', ISO3: 'MUS', ISO2: 'MU'}; break;
    case 'MEX' : return { countryName: 'Mexico', FIFA: 'MEX', ISO3: 'MEX', ISO2: 'MX'}; break;
    case 'MDA' : return { countryName: 'Moldova', FIFA: 'MDA', ISO3: 'MDA', ISO2: 'MD'}; break;
    case 'MNG' : return { countryName: 'Mongolia', FIFA: 'MNG', ISO3: 'MNG', ISO2: 'MN'}; break;
    case 'MNE' : return { countryName: 'Montenegro', FIFA: 'MNE', ISO3: 'MNE', ISO2: 'ME'}; break;
    case 'MAR' : return { countryName: 'Morocco', FIFA: 'MAR', ISO3: 'MAR', ISO2: 'MA'}; break;
    case 'MOZ' : return { countryName: 'Mozambique', FIFA: 'MOZ', ISO3: 'MOZ', ISO2: 'MZ'}; break;
    case 'MYA' : return { countryName: 'Myanmar', FIFA: 'MYA', ISO3: 'MMR', ISO2: 'MM'}; break;
    case 'NAM' : return { countryName: 'Namibia', FIFA: 'NAM', ISO3: 'NAM', ISO2: 'NA'}; break;
    case 'NEP' : return { countryName: 'Nepal', FIFA: 'NEP', ISO3: 'NPL', ISO2: 'NP'}; break;
    case 'NED' : return { countryName: 'Netherlands', FIFA: 'NED', ISO3: 'NLD', ISO2: 'NL'}; break;
    case 'NZL' : return { countryName: 'New Zealand', FIFA: 'NZL', ISO3: 'NZL', ISO2: 'NZ'}; break;
    case 'NCA' : return { countryName: 'Nicaragua', FIFA: 'NCA', ISO3: 'NIC', ISO2: 'NI'}; break;
    case 'NIG' : return { countryName: 'Niger', FIFA: 'NIG', ISO3: 'NER', ISO2: 'NE'}; break;
    case 'NGA' : return { countryName: 'Nigeria', FIFA: 'NGA', ISO3: 'NGA', ISO2: 'NG'}; break;
    case 'NOR' : return { countryName: 'Norway', FIFA: 'NOR', ISO3: 'NOR', ISO2: 'NO'}; break;
    case 'OMA' : return { countryName: 'Oman', FIFA: 'OMA', ISO3: 'OMN', ISO2: 'OM'}; break;
    case 'PAK' : return { countryName: 'Pakistan', FIFA: 'PAK', ISO3: 'PAK', ISO2: 'PK'}; break;
    case 'PLE' : return { countryName: 'Palestinian Authority', FIFA: 'PLE', ISO3: 'PSE', ISO2: 'PS'}; break;
    case 'PAN' : return { countryName: 'Panama', FIFA: 'PAN', ISO3: 'PAN', ISO2: 'PA'}; break;
    case 'PNG' : return { countryName: 'Papua New Guinea', FIFA: 'PNG', ISO3: 'PNG', ISO2: 'PG'}; break;
    case 'PAR' : return { countryName: 'Paraguay', FIFA: 'PAR', ISO3: 'PRY', ISO2: 'PY'}; break;
    case 'PER' : return { countryName: 'Peru', FIFA: 'PER', ISO3: 'PER', ISO2: 'PE'}; break;
    case 'PHI' : return { countryName: 'Philippines', FIFA: 'PHI', ISO3: 'PHL', ISO2: 'PH'}; break;
    case 'POL' : return { countryName: 'Poland', FIFA: 'POL', ISO3: 'POL', ISO2: 'PL'}; break;
    case 'POR' : return { countryName: 'Portugal', FIFA: 'POR', ISO3: 'PRT', ISO2: 'PT'}; break;
    case 'PUR' : return { countryName: 'Puerto Rico', FIFA: 'PUR', ISO3: 'PRI', ISO2: 'PR'}; break;
    case 'QAT' : return { countryName: 'Qatar', FIFA: 'QAT', ISO3: 'QAT', ISO2: 'QA'}; break;
    case 'ROU' : return { countryName: 'Romania', FIFA: 'ROU', ISO3: 'ROU', ISO2: 'RO'}; break;
    case 'RUS' : return { countryName: 'Russia', FIFA: 'RUS', ISO3: 'RUS', ISO2: 'RU'}; break;
    case 'RWA' : return { countryName: 'Rwanda', FIFA: 'RWA', ISO3: 'RWA', ISO2: 'RW'}; break;
    case 'SKN' : return { countryName: 'Saint Kitts and Nevis', FIFA: 'SKN', ISO3: 'KNA', ISO2: 'KN'}; break;
    case 'LCA' : return { countryName: 'Saint Lucia', FIFA: 'LCA', ISO3: 'LCA', ISO2: 'LC'}; break;
    case 'VIN' : return { countryName: 'Saint Vincent and the Grenadines', FIFA: 'VIN', ISO3: 'VCT', ISO2: 'VC'}; break;
    case 'SAM' : return { countryName: 'Samoa', FIFA: 'SAM', ISO3: 'WSM', ISO2: 'WS'}; break;
    case 'SMR' : return { countryName: 'San Marino', FIFA: 'SMR', ISO3: 'SMR', ISO2: 'SM'}; break;
    case 'STP' : return { countryName: 'São Tomé and Príncipe', FIFA: 'STP', ISO3: 'STP', ISO2: 'ST'}; break;
    case 'KSA' : return { countryName: 'Saudi Arabia', FIFA: 'KSA', ISO3: 'SAU', ISO2: 'SA'}; break;
    case 'SEN' : return { countryName: 'Senegal', FIFA: 'SEN', ISO3: 'SEN', ISO2: 'SN'}; break;
    case 'SRB' : return { countryName: 'Serbia', FIFA: 'SRB', ISO3: 'SRB', ISO2: 'RS'}; break;
    case 'SEY' : return { countryName: 'Seychelles', FIFA: 'SEY', ISO3: 'SYC', ISO2: 'SC'}; break;
    case 'SLE' : return { countryName: 'Sierra Leone', FIFA: 'SLE', ISO3: 'SLE', ISO2: 'SL'}; break;
    case 'SIN' : return { countryName: 'Singapore', FIFA: 'SIN', ISO3: 'SGP', ISO2: 'SG'}; break;
    case 'SVK' : return { countryName: 'Slovakia', FIFA: 'SVK', ISO3: 'SVK', ISO2: 'SK'}; break;
    case 'SVN' : return { countryName: 'Slovenia', FIFA: 'SVN', ISO3: 'SVN', ISO2: 'SI'}; break;
    case 'SOL' : return { countryName: 'Solomon Islands', FIFA: 'SOL', ISO3: 'SLB', ISO2: 'SB'}; break;
    case 'SOM' : return { countryName: 'Somalia', FIFA: 'SOM', ISO3: 'SOM', ISO2: 'SO'}; break;
    case 'RSA' : return { countryName: 'South Africa', FIFA: 'RSA', ISO3: 'ZAF', ISO2: 'ZA'}; break;
    case 'ESP' : return { countryName: 'Spain', FIFA: 'ESP', ISO3: 'ESP', ISO2: 'ES'}; break;
    case 'SRI' : return { countryName: 'Sri Lanka', FIFA: 'SRI', ISO3: 'LKA', ISO2: 'LK'}; break;
    case 'SDN' : return { countryName: 'Sudan', FIFA: 'SDN', ISO3: 'SDN', ISO2: 'SD'}; break;
    case 'SUR' : return { countryName: 'Suriname', FIFA: 'SUR', ISO3: 'SUR', ISO2: 'SR'}; break;
    case 'SWZ' : return { countryName: 'Eswatini', FIFA: 'SWZ', ISO3: 'SWZ', ISO2: 'SZ'}; break;
    case 'SWE' : return { countryName: 'Sweden', FIFA: 'SWE', ISO3: 'SWE', ISO2: 'SE'}; break;
    case 'SUI' : return { countryName: 'Switzerland', FIFA: 'SUI', ISO3: 'CHE', ISO2: 'CH'}; break;
    case 'SYR' : return { countryName: 'Syria', FIFA: 'SYR', ISO3: 'SYR', ISO2: 'SY'}; break;
    case 'TPE' : return { countryName: 'Taiwan', FIFA: 'TPE', ISO3: 'TWN', ISO2: 'TW'}; break;
    case 'TJK' : return { countryName: 'Tajikistan', FIFA: 'TJK', ISO3: 'TJK', ISO2: 'TJ'}; break;
    case 'TAN' : return { countryName: 'Tanzania', FIFA: 'TAN', ISO3: 'TZA', ISO2: 'TZ'}; break;
    case 'THA' : return { countryName: 'Thailand', FIFA: 'THA', ISO3: 'THA', ISO2: 'TH'}; break;
    case 'TLS' : return { countryName: 'Timor-Leste', FIFA: 'TLS', ISO3: 'TLS', ISO2: 'TL'}; break;
    case 'TOG' : return { countryName: 'Togo', FIFA: 'TOG', ISO3: 'TGO', ISO2: 'TG'}; break;
    case 'TGA' : return { countryName: 'Tonga', FIFA: 'TGA', ISO3: 'TON', ISO2: 'TO'}; break;
    case 'TRI' : return { countryName: 'Trinidad and Tobago', FIFA: 'TRI', ISO3: 'TTO', ISO2: 'TT'}; break;
    case 'TUN' : return { countryName: 'Tunisia', FIFA: 'TUN', ISO3: 'TUN', ISO2: 'TN'}; break;
    case 'TUR' : return { countryName: 'Turkey', FIFA: 'TUR', ISO3: 'TUR', ISO2: 'TR'}; break;
    case 'TKM' : return { countryName: 'Turkmenistan', FIFA: 'TKM', ISO3: 'TKM', ISO2: 'TM'}; break;
    case 'TCA' : return { countryName: 'Turks and Caicos Islands', FIFA: 'TCA', ISO3: 'TCA', ISO2: 'TC'}; break;
    case 'UGA' : return { countryName: 'Uganda', FIFA: 'UGA', ISO3: 'UGA', ISO2: 'UG'}; break;
    case 'UKR' : return { countryName: 'Ukraine', FIFA: 'UKR', ISO3: 'UKR', ISO2: 'UA'}; break;
    case 'UAE' : return { countryName: 'United Arab Emirates', FIFA: 'UAE', ISO3: 'ARE', ISO2: 'AE'}; break;
    case 'USA' : return { countryName: 'United States', FIFA: 'USA', ISO3: 'USA', ISO2: 'US'}; break;
    case 'VIR' : return { countryName: 'United States Virgin Islands', FIFA: 'VIR', ISO3: 'VIR', ISO2: 'VI'}; break;
    case 'URU' : return { countryName: 'Uruguay', FIFA: 'URU', ISO3: 'URY', ISO2: 'UY'}; break;
    case 'UZB' : return { countryName: 'Uzbekistan', FIFA: 'UZB', ISO3: 'UZB', ISO2: 'UZ'}; break;
    case 'VAN' : return { countryName: 'Vanuatu', FIFA: 'VAN', ISO3: 'VUT', ISO2: 'VU'}; break;
    case 'VEN' : return { countryName: 'Venezuela', FIFA: 'VEN', ISO3: 'VEN', ISO2: 'VE'}; break;
    case 'VIE' : return { countryName: 'Vietnam', FIFA: 'VIE', ISO3: 'VNM', ISO2: 'VN'}; break;
    case 'YEM' : return { countryName: 'Yemen', FIFA: 'YEM', ISO3: 'YEM', ISO2: 'YE'}; break;
    case 'ZAM' : return { countryName: 'Zambia', FIFA: 'ZAM', ISO3: 'ZMB', ISO2: 'ZM'}; break;
    case 'ZIM' : return { countryName: 'Zimbabwe', FIFA: 'ZIM', ISO3: 'ZWE', ISO2: 'ZW'}; break;
    case 'GBR' : return { countryName: 'United Kingdom', FIFA: 'GBR', ISO3: 'GBR', ISO2: 'GB'}; break;
    default: return { FIFA: "IOC", ISO3: "IOC", ISO2: "IOC" }; break;
  }

}

exports.convertFIFACountryCode = function (FIFACountryCode) {

  switch (FIFACountryCode.toUpperCase()) {
    case 'AFG' : return { countryName: 'Afghanistan', IOC: 'AFG', ISO3: 'AFG', ISO2: 'AF'}; break;
    case 'ALB' : return { countryName: 'Albania', IOC: 'ALB', ISO3: 'ALB', ISO2: 'AL'}; break;
    case 'ALG' : return { countryName: 'Algeria', IOC: 'ALG', ISO3: 'DZA', ISO2: 'DZ'}; break;
    case 'ASA' : return { countryName: 'American Samoa', IOC: 'ASA', ISO3: 'ASM', ISO2: 'AS'}; break;
    case 'AND' : return { countryName: 'Andorra', IOC: 'AND', ISO3: 'AND', ISO2: 'AD'}; break;
    case 'ANG' : return { countryName: 'Angola', IOC: 'ANG', ISO3: 'AGO', ISO2: 'AO'}; break;
    case 'ATG' : return { countryName: 'Antigua and Barbuda', IOC: 'ANT', ISO3: 'ATG', ISO2: 'AG'}; break;
    case 'ARG' : return { countryName: 'Argentina', IOC: 'ARG', ISO3: 'ARG', ISO2: 'AR'}; break;
    case 'ARM' : return { countryName: 'Armenia', IOC: 'ARM', ISO3: 'ARM', ISO2: 'AM'}; break;
    case 'ARU' : return { countryName: 'Aruba', IOC: 'ARU', ISO3: 'ABW', ISO2: 'AW'}; break;
    case 'AUS' : return { countryName: 'Australia', IOC: 'AUS', ISO3: 'AUS', ISO2: 'AU'}; break;
    case 'AUT' : return { countryName: 'Austria', IOC: 'AUT', ISO3: 'AUT', ISO2: 'AT'}; break;
    case 'AZE' : return { countryName: 'Azerbaijan', IOC: 'AZE', ISO3: 'AZE', ISO2: 'AZ'}; break;
    case 'BAH' : return { countryName: 'The Bahamas', IOC: 'BAH', ISO3: 'BHS', ISO2: 'BS'}; break;
    case 'BHR' : return { countryName: 'Bahrain', IOC: 'BRN', ISO3: 'BHR', ISO2: 'BH'}; break;
    case 'BAN' : return { countryName: 'Bangladesh', IOC: 'BAN', ISO3: 'BGD', ISO2: 'BD'}; break;
    case 'BRB' : return { countryName: 'Barbados', IOC: 'BAR', ISO3: 'BRB', ISO2: 'BB'}; break;
    case 'BLR' : return { countryName: 'Belarus', IOC: 'BLR', ISO3: 'BLR', ISO2: 'BY'}; break;
    case 'BEL' : return { countryName: 'Belgium', IOC: 'BEL', ISO3: 'BEL', ISO2: 'BE'}; break;
    case 'BLZ' : return { countryName: 'Belize', IOC: 'BIZ', ISO3: 'BLZ', ISO2: 'BZ'}; break;
    case 'BEN' : return { countryName: 'Benin', IOC: 'BEN', ISO3: 'BEN', ISO2: 'BJ'}; break;
    case 'BER' : return { countryName: 'Bermuda', IOC: 'BER', ISO3: 'BMU', ISO2: 'BM'}; break;
    case 'BHU' : return { countryName: 'Bhutan', IOC: 'BHU', ISO3: 'BTN', ISO2: 'BT'}; break;
    case 'BOL' : return { countryName: 'Bolivia', IOC: 'BOL', ISO3: 'BOL', ISO2: 'BO'}; break;
    case 'BIH' : return { countryName: 'Bosnia and Herzegovina', IOC: 'BIH', ISO3: 'BIH', ISO2: 'BA'}; break;
    case 'BOT' : return { countryName: 'Botswana', IOC: 'BOT', ISO3: 'BWA', ISO2: 'BW'}; break;
    case 'BRA' : return { countryName: 'Brazil', IOC: 'BRA', ISO3: 'BRA', ISO2: 'BR'}; break;
    case 'VGB' : return { countryName: 'British Virgin Islands', IOC: 'IVB', ISO3: 'VGB', ISO2: 'VG'}; break;
    case 'BRU' : return { countryName: 'Brunei', IOC: 'BRU', ISO3: 'BRN', ISO2: 'BN'}; break;
    case 'BUL' : return { countryName: 'Bulgaria', IOC: 'BUL', ISO3: 'BGR', ISO2: 'BG'}; break;
    case 'BFA' : return { countryName: 'Burkina Faso', IOC: 'BUR', ISO3: 'BFA', ISO2: 'BF'}; break;
    case 'BDI' : return { countryName: 'Burundi', IOC: 'BDI', ISO3: 'BDI', ISO2: 'BI'}; break;
    case 'CAM' : return { countryName: 'Cambodia', IOC: 'CAM', ISO3: 'KHM', ISO2: 'KH'}; break;
    case 'CMR' : return { countryName: 'Cameroon', IOC: 'CMR', ISO3: 'CMR', ISO2: 'CM'}; break;
    case 'CAN' : return { countryName: 'Canada', IOC: 'CAN', ISO3: 'CAN', ISO2: 'CA'}; break;
    case 'CPV' : return { countryName: 'Cape Verde', IOC: 'CPV', ISO3: 'CPV', ISO2: 'CV'}; break;
    case 'CAY' : return { countryName: 'Cayman Islands', IOC: 'CAY', ISO3: 'CYM', ISO2: 'KY'}; break;
    case 'CTA' : return { countryName: 'Central African Republic', IOC: 'CAF', ISO3: 'CAF', ISO2: 'CF'}; break;
    case 'CHA' : return { countryName: 'Chad', IOC: 'CHA', ISO3: 'TCD', ISO2: 'TD'}; break;
    case 'CHI' : return { countryName: 'Chile', IOC: 'CHI', ISO3: 'CHL', ISO2: 'CL'}; break;
    case 'CHN' : return { countryName: 'China', IOC: 'CHN', ISO3: 'CHN', ISO2: 'CN'}; break;
    case 'COL' : return { countryName: 'Colombia', IOC: 'COL', ISO3: 'COL', ISO2: 'CO'}; break;
    case 'COM' : return { countryName: 'Comoros', IOC: 'COM', ISO3: 'COM', ISO2: 'KM'}; break;
    case 'COD' : return { countryName: 'Democratic Republic of Congo', IOC: 'COD', ISO3: 'COD', ISO2: 'CD'}; break;
    case 'CGO' : return { countryName: 'Republic of Congo', IOC: 'CGO', ISO3: 'COG', ISO2: 'CG'}; break;
    case 'COK' : return { countryName: 'Cook Islands', IOC: 'COK', ISO3: 'COK', ISO2: 'CK'}; break;
    case 'CRC' : return { countryName: 'Costa Rica', IOC: 'CRC', ISO3: 'CRI', ISO2: 'CR'}; break;
    case 'CIV' : return { countryName: "Côte d'Ivoire", IOC: 'CIV', ISO3: 'CIV', ISO2: 'CI'}; break;
    case 'CRO' : return { countryName: 'Croatia', IOC: 'CRO', ISO3: 'HRV', ISO2: 'HR'}; break;
    case 'CUB' : return { countryName: 'Cuba', IOC: 'CUB', ISO3: 'CUB', ISO2: 'CU'}; break;
    case 'CYP' : return { countryName: 'Cyprus', IOC: 'CYP', ISO3: 'CYP', ISO2: 'CY'}; break;
    case 'CZE' : return { countryName: 'Czech Republic', IOC: 'CZE', ISO3: 'CZE', ISO2: 'CZ'}; break;
    case 'DEN' : return { countryName: 'Denmark', IOC: 'DEN', ISO3: 'DNK', ISO2: 'DK'}; break;
    case 'DJI' : return { countryName: 'Djibouti', IOC: 'DJI', ISO3: 'DJI', ISO2: 'DJ'}; break;
    case 'DMA' : return { countryName: 'Dominica', IOC: 'DMA', ISO3: 'DMA', ISO2: 'DM'}; break;
    case 'DOM' : return { countryName: 'Dominican Republic', IOC: 'DOM', ISO3: 'DOM', ISO2: 'DO'}; break;
    case 'ECU' : return { countryName: 'Ecuador', IOC: 'ECU', ISO3: 'ECU', ISO2: 'EC'}; break;
    case 'EGY' : return { countryName: 'Egypt', IOC: 'EGY', ISO3: 'EGY', ISO2: 'EG'}; break;
    case 'SLV' : return { countryName: 'El Salvador', IOC: 'ESA', ISO3: 'SLV', ISO2: 'SV'}; break;
    case 'EQG' : return { countryName: 'Equatorial Guinea', IOC: 'GEQ', ISO3: 'GNQ', ISO2: 'GQ'}; break;
    case 'ERI' : return { countryName: 'Eritrea', IOC: 'ERI', ISO3: 'ERI', ISO2: 'ER'}; break;
    case 'EST' : return { countryName: 'Estonia', IOC: 'EST', ISO3: 'EST', ISO2: 'EE'}; break;
    case 'ETH' : return { countryName: 'Ethiopia', IOC: 'ETH', ISO3: 'ETH', ISO2: 'ET'}; break;
    case 'FIJ' : return { countryName: 'Fiji', IOC: 'FIJ', ISO3: 'FJI', ISO2: 'FJ'}; break;
    case 'FIN' : return { countryName: 'Finland', IOC: 'FIN', ISO3: 'FIN', ISO2: 'FI'}; break;
    case 'FRA' : return { countryName: 'France', IOC: 'FRA', ISO3: 'FRA', ISO2: 'FR'}; break;
    case 'TAH' : return { countryName: 'French Polynesia', IOC: 'FPN', ISO3: 'PYF', ISO2: 'PF'}; break;
    case 'GAB' : return { countryName: 'Gabon', IOC: 'GAB', ISO3: 'GAB', ISO2: 'GA'}; break;
    case 'GAM' : return { countryName: 'The Gambia', IOC: 'GAM', ISO3: 'GMB', ISO2: 'GM'}; break;
    case 'GEO' : return { countryName: 'Georgia', IOC: 'GEO', ISO3: 'GEO', ISO2: 'GE'}; break;
    case 'GER' : return { countryName: 'Germany', IOC: 'GER', ISO3: 'DEU', ISO2: 'DE'}; break;
    case 'GHA' : return { countryName: 'Ghana', IOC: 'GHA', ISO3: 'GHA', ISO2: 'GH'}; break;
    case 'GRE' : return { countryName: 'Greece', IOC: 'GRE', ISO3: 'GRC', ISO2: 'GR'}; break;
    case 'GRN' : return { countryName: 'Grenada', IOC: 'GRN', ISO3: 'GRD', ISO2: 'GD'}; break;
    case 'GUM' : return { countryName: 'Guam', IOC: 'GUM', ISO3: 'GUM', ISO2: 'GU'}; break;
    case 'GUA' : return { countryName: 'Guatemala', IOC: 'GUA', ISO3: 'GTM', ISO2: 'GT'}; break;
    case 'GUI' : return { countryName: 'Guinea', IOC: 'GUI', ISO3: 'GIN', ISO2: 'GN'}; break;
    case 'GNB' : return { countryName: 'Guinea-Bissau', IOC: 'GBS', ISO3: 'GNB', ISO2: 'GW'}; break;
    case 'GUY' : return { countryName: 'Guyana', IOC: 'GUY', ISO3: 'GUY', ISO2: 'GY'}; break;
    case 'HAI' : return { countryName: 'Haiti', IOC: 'HAI', ISO3: 'HTI', ISO2: 'HT'}; break;
    case 'HON' : return { countryName: 'Honduras', IOC: 'HON', ISO3: 'HND', ISO2: 'HN'}; break;
    case 'HKG' : return { countryName: 'Hong Kong', IOC: 'HKG', ISO3: 'HKG', ISO2: 'HK'}; break;
    case 'HUN' : return { countryName: 'Hungary', IOC: 'HUN', ISO3: 'HUN', ISO2: 'HU'}; break;
    case 'ISL' : return { countryName: 'Iceland', IOC: 'ISL', ISO3: 'ISL', ISO2: 'IS'}; break;
    case 'IND' : return { countryName: 'India', IOC: 'IND', ISO3: 'IND', ISO2: 'IN'}; break;
    case 'IDN' : return { countryName: 'Indonesia', IOC: 'INA', ISO3: 'IDN', ISO2: 'ID'}; break;
    case 'IRN' : return { countryName: 'Iran', IOC: 'IRI', ISO3: 'IRN', ISO2: 'IR'}; break;
    case 'IRQ' : return { countryName: 'Iraq', IOC: 'IRQ', ISO3: 'IRQ', ISO2: 'IQ'}; break;
    case 'IRL' : return { countryName: 'Ireland', IOC: 'IRL', ISO3: 'IRL', ISO2: 'IE'}; break;
    case 'ISR' : return { countryName: 'Israel', IOC: 'ISR', ISO3: 'ISR', ISO2: 'IL'}; break;
    case 'ITA' : return { countryName: 'Italy', IOC: 'ITA', ISO3: 'ITA', ISO2: 'IT'}; break;
    case 'JAM' : return { countryName: 'Jamaica', IOC: 'JAM', ISO3: 'JAM', ISO2: 'JM'}; break;
    case 'JPN' : return { countryName: 'Japan', IOC: 'JPN', ISO3: 'JPN', ISO2: 'JP'}; break;
    case 'JOR' : return { countryName: 'Jordan', IOC: 'JOR', ISO3: 'JOR', ISO2: 'JO'}; break;
    case 'KAZ' : return { countryName: 'Kazakhstan', IOC: 'KAZ', ISO3: 'KAZ', ISO2: 'KZ'}; break;
    case 'KEN' : return { countryName: 'Kenya', IOC: 'KEN', ISO3: 'KEN', ISO2: 'KE'}; break;
    case 'PRK' : return { countryName: 'North Korea', IOC: 'PRK', ISO3: 'PRK', ISO2: 'KP'}; break;
    case 'KOR' : return { countryName: 'South Korea', IOC: 'KOR', ISO3: 'KOR', ISO2: 'KR'}; break;
    case 'KUW' : return { countryName: 'Kuwait', IOC: 'KUW', ISO3: 'KWT', ISO2: 'KW'}; break;
    case 'KGZ' : return { countryName: 'Kyrgyzstan', IOC: 'KGZ', ISO3: 'KGZ', ISO2: 'KG'}; break;
    case 'LAO' : return { countryName: 'Laos', IOC: 'LAO', ISO3: 'LAO', ISO2: 'LA'}; break;
    case 'LVA' : return { countryName: 'Latvia', IOC: 'LAT', ISO3: 'LVA', ISO2: 'LV'}; break;
    case 'LBN' : return { countryName: 'Lebanon', IOC: 'LIB', ISO3: 'LBN', ISO2: 'LB'}; break;
    case 'LES' : return { countryName: 'Lesotho', IOC: 'LES', ISO3: 'LSO', ISO2: 'LS'}; break;
    case 'LBR' : return { countryName: 'Liberia', IOC: 'LBR', ISO3: 'LBR', ISO2: 'LR'}; break;
    case 'LBY' : return { countryName: 'Libya', IOC: 'LBA', ISO3: 'LBY', ISO2: 'LY'}; break;
    case 'LIE' : return { countryName: 'Liechtenstein', IOC: 'LIE', ISO3: 'LIE', ISO2: 'LI'}; break;
    case 'LTU' : return { countryName: 'Lithuania', IOC: 'LTU', ISO3: 'LTU', ISO2: 'LT'}; break;
    case 'LUX' : return { countryName: 'Luxembourg', IOC: 'LUX', ISO3: 'LUX', ISO2: 'LU'}; break;
    case 'MKD' : return { countryName: 'Macedonia', IOC: 'MKD', ISO3: 'MKD', ISO2: 'MK'}; break;
    case 'MAD' : return { countryName: 'Madagascar', IOC: 'MAD', ISO3: 'MDG', ISO2: 'MG'}; break;
    case 'MWI' : return { countryName: 'Malawi', IOC: 'MAW', ISO3: 'MWI', ISO2: 'MW'}; break;
    case 'MAS' : return { countryName: 'Malaysia', IOC: 'MAS', ISO3: 'MYS', ISO2: 'MY'}; break;
    case 'MDV' : return { countryName: 'Maldives', IOC: 'MDV', ISO3: 'MDV', ISO2: 'MV'}; break;
    case 'MLI' : return { countryName: 'Mali', IOC: 'MLI', ISO3: 'MLI', ISO2: 'ML'}; break;
    case 'MLT' : return { countryName: 'Malta', IOC: 'MLT', ISO3: 'MLT', ISO2: 'MT'}; break;
    case 'MTN' : return { countryName: 'Mauritania', IOC: 'MTN', ISO3: 'MRT', ISO2: 'MR'}; break;
    case 'MRI' : return { countryName: 'Mauritius', IOC: 'MRI', ISO3: 'MUS', ISO2: 'MU'}; break;
    case 'MEX' : return { countryName: 'Mexico', IOC: 'MEX', ISO3: 'MEX', ISO2: 'MX'}; break;
    case 'MDA' : return { countryName: 'Moldova', IOC: 'MDA', ISO3: 'MDA', ISO2: 'MD'}; break;
    case 'MNG' : return { countryName: 'Mongolia', IOC: 'MGL', ISO3: 'MNG', ISO2: 'MN'}; break;
    case 'MNE' : return { countryName: 'Montenegro', IOC: 'MNE', ISO3: 'MNE', ISO2: 'ME'}; break;
    case 'MAR' : return { countryName: 'Morocco', IOC: 'MAR', ISO3: 'MAR', ISO2: 'MA'}; break;
    case 'MOZ' : return { countryName: 'Mozambique', IOC: 'MOZ', ISO3: 'MOZ', ISO2: 'MZ'}; break;
    case 'MYA' : return { countryName: 'Myanmar', IOC: 'MYA', ISO3: 'MMR', ISO2: 'MM'}; break;
    case 'NAM' : return { countryName: 'Namibia', IOC: 'NAM', ISO3: 'NAM', ISO2: 'NA'}; break;
    case 'NEP' : return { countryName: 'Nepal', IOC: 'NEP', ISO3: 'NPL', ISO2: 'NP'}; break;
    case 'NED' : return { countryName: 'Netherlands', IOC: 'NED', ISO3: 'NLD', ISO2: 'NL'}; break;
    case 'NZL' : return { countryName: 'New Zealand', IOC: 'NZL', ISO3: 'NZL', ISO2: 'NZ'}; break;
    case 'NCA' : return { countryName: 'Nicaragua', IOC: 'NCA', ISO3: 'NIC', ISO2: 'NI'}; break;
    case 'NIG' : return { countryName: 'Niger', IOC: 'NIG', ISO3: 'NER', ISO2: 'NE'}; break;
    case 'NGA' : return { countryName: 'Nigeria', IOC: 'NGR', ISO3: 'NGA', ISO2: 'NG'}; break;
    case 'NOR' : return { countryName: 'Norway', IOC: 'NOR', ISO3: 'NOR', ISO2: 'NO'}; break;
    case 'OMA' : return { countryName: 'Oman', IOC: 'OMA', ISO3: 'OMN', ISO2: 'OM'}; break;
    case 'PAK' : return { countryName: 'Pakistan', IOC: 'PAK', ISO3: 'PAK', ISO2: 'PK'}; break;
    case 'PLE' : return { countryName: 'Palestinian Authority', IOC: 'PLE', ISO3: 'PSE', ISO2: 'PS'}; break;
    case 'PAN' : return { countryName: 'Panama', IOC: 'PAN', ISO3: 'PAN', ISO2: 'PA'}; break;
    case 'PNG' : return { countryName: 'Papua New Guinea', IOC: 'PNG', ISO3: 'PNG', ISO2: 'PG'}; break;
    case 'PAR' : return { countryName: 'Paraguay', IOC: 'PAR', ISO3: 'PRY', ISO2: 'PY'}; break;
    case 'PER' : return { countryName: 'Peru', IOC: 'PER', ISO3: 'PER', ISO2: 'PE'}; break;
    case 'PHI' : return { countryName: 'Philippines', IOC: 'PHI', ISO3: 'PHL', ISO2: 'PH'}; break;
    case 'POL' : return { countryName: 'Poland', IOC: 'POL', ISO3: 'POL', ISO2: 'PL'}; break;
    case 'POR' : return { countryName: 'Portugal', IOC: 'POR', ISO3: 'PRT', ISO2: 'PT'}; break;
    case 'PUR' : return { countryName: 'Puerto Rico', IOC: 'PUR', ISO3: 'PRI', ISO2: 'PR'}; break;
    case 'QAT' : return { countryName: 'Qatar', IOC: 'QAT', ISO3: 'QAT', ISO2: 'QA'}; break;
    case 'ROU' : return { countryName: 'Romania', IOC: 'ROU', ISO3: 'ROU', ISO2: 'RO'}; break;
    case 'RUS' : return { countryName: 'Russia', IOC: 'RUS', ISO3: 'RUS', ISO2: 'RU'}; break;
    case 'RWA' : return { countryName: 'Rwanda', IOC: 'RWA', ISO3: 'RWA', ISO2: 'RW'}; break;
    case 'SKN' : return { countryName: 'Saint Kitts and Nevis', IOC: 'SKN', ISO3: 'KNA', ISO2: 'KN'}; break;
    case 'LCA' : return { countryName: 'Saint Lucia', IOC: 'LCA', ISO3: 'LCA', ISO2: 'LC'}; break;
    case 'VIN' : return { countryName: 'Saint Vincent and the Grenadines', IOC: 'VIN', ISO3: 'VCT', ISO2: 'VC'}; break;
    case 'SAM' : return { countryName: 'Samoa', IOC: 'SAM', ISO3: 'WSM', ISO2: 'WS'}; break;
    case 'SMR' : return { countryName: 'San Marino', IOC: 'SMR', ISO3: 'SMR', ISO2: 'SM'}; break;
    case 'STP' : return { countryName: 'São Tomé and Príncipe', IOC: 'STP', ISO3: 'STP', ISO2: 'ST'}; break;
    case 'KSA' : return { countryName: 'Saudi Arabia', IOC: 'KSA', ISO3: 'SAU', ISO2: 'SA'}; break;
    case 'SEN' : return { countryName: 'Senegal', IOC: 'SEN', ISO3: 'SEN', ISO2: 'SN'}; break;
    case 'SRB' : return { countryName: 'Serbia', IOC: 'SRB', ISO3: 'SRB', ISO2: 'RS'}; break;
    case 'SEY' : return { countryName: 'Seychelles', IOC: 'SEY', ISO3: 'SYC', ISO2: 'SC'}; break;
    case 'SLE' : return { countryName: 'Sierra Leone', IOC: 'SLE', ISO3: 'SLE', ISO2: 'SL'}; break;
    case 'SIN' : return { countryName: 'Singapore', IOC: 'SGP', ISO3: 'SGP', ISO2: 'SG'}; break;
    case 'SVK' : return { countryName: 'Slovakia', IOC: 'SVK', ISO3: 'SVK', ISO2: 'SK'}; break;
    case 'SVN' : return { countryName: 'Slovenia', IOC: 'SLO', ISO3: 'SVN', ISO2: 'SI'}; break;
    case 'SOL' : return { countryName: 'Solomon Islands', IOC: 'SOL', ISO3: 'SLB', ISO2: 'SB'}; break;
    case 'SOM' : return { countryName: 'Somalia', IOC: 'SOM', ISO3: 'SOM', ISO2: 'SO'}; break;
    case 'RSA' : return { countryName: 'South Africa', IOC: 'RSA', ISO3: 'ZAF', ISO2: 'ZA'}; break;
    case 'ESP' : return { countryName: 'Spain', IOC: 'ESP', ISO3: 'ESP', ISO2: 'ES'}; break;
    case 'SRI' : return { countryName: 'Sri Lanka', IOC: 'SRI', ISO3: 'LKA', ISO2: 'LK'}; break;
    case 'SDN' : return { countryName: 'Sudan', IOC: 'SUD', ISO3: 'SDN', ISO2: 'SD'}; break;
    case 'SUR' : return { countryName: 'Suriname', IOC: 'SUR', ISO3: 'SUR', ISO2: 'SR'}; break;
    case 'SWZ' : return { countryName: 'Eswatini', IOC: 'SWZ', ISO3: 'SWZ', ISO2: 'SZ'}; break;
    case 'SWE' : return { countryName: 'Sweden', IOC: 'SWE', ISO3: 'SWE', ISO2: 'SE'}; break;
    case 'SUI' : return { countryName: 'Switzerland', IOC: 'SUI', ISO3: 'CHE', ISO2: 'CH'}; break;
    case 'SYR' : return { countryName: 'Syria', IOC: 'SYR', ISO3: 'SYR', ISO2: 'SY'}; break;
    case 'TPE' : return { countryName: 'Taiwan', IOC: 'TPE', ISO3: 'TWN', ISO2: 'TW'}; break;
    case 'TJK' : return { countryName: 'Tajikistan', IOC: 'TJK', ISO3: 'TJK', ISO2: 'TJ'}; break;
    case 'TAN' : return { countryName: 'Tanzania', IOC: 'TAN', ISO3: 'TZA', ISO2: 'TZ'}; break;
    case 'THA' : return { countryName: 'Thailand', IOC: 'THA', ISO3: 'THA', ISO2: 'TH'}; break;
    case 'TLS' : return { countryName: 'Timor-Leste', IOC: 'TLS', ISO3: 'TLS', ISO2: 'TL'}; break;
    case 'TOG' : return { countryName: 'Togo', IOC: 'TOG', ISO3: 'TGO', ISO2: 'TG'}; break;
    case 'TGA' : return { countryName: 'Tonga', IOC: 'TGA', ISO3: 'TON', ISO2: 'TO'}; break;
    case 'TRI' : return { countryName: 'Trinidad and Tobago', IOC: 'TTO', ISO3: 'TTO', ISO2: 'TT'}; break;
    case 'TUN' : return { countryName: 'Tunisia', IOC: 'TUN', ISO3: 'TUN', ISO2: 'TN'}; break;
    case 'TUR' : return { countryName: 'Turkey', IOC: 'TUR', ISO3: 'TUR', ISO2: 'TR'}; break;
    case 'TKM' : return { countryName: 'Turkmenistan', IOC: 'TKM', ISO3: 'TKM', ISO2: 'TM'}; break;
    case 'TCA' : return { countryName: 'Turks and Caicos Islands', IOC: 'TCA', ISO3: 'TCA', ISO2: 'TC'}; break;
    case 'UGA' : return { countryName: 'Uganda', IOC: 'UGA', ISO3: 'UGA', ISO2: 'UG'}; break;
    case 'UKR' : return { countryName: 'Ukraine', IOC: 'UKR', ISO3: 'UKR', ISO2: 'UA'}; break;
    case 'UAE' : return { countryName: 'United Arab Emirates', IOC: 'UAE', ISO3: 'ARE', ISO2: 'AE'}; break;
    case 'USA' : return { countryName: 'United States', IOC: 'USA', ISO3: 'USA', ISO2: 'US'}; break;
    case 'VIR' : return { countryName: 'United States Virgin Islands', IOC: 'ISV', ISO3: 'VIR', ISO2: 'VI'}; break;
    case 'URU' : return { countryName: 'Uruguay', IOC: 'URU', ISO3: 'URY', ISO2: 'UY'}; break;
    case 'UZB' : return { countryName: 'Uzbekistan', IOC: 'UZB', ISO3: 'UZB', ISO2: 'UZ'}; break;
    case 'VAN' : return { countryName: 'Vanuatu', IOC: 'VAN', ISO3: 'VUT', ISO2: 'VU'}; break;
    case 'VEN' : return { countryName: 'Venezuela', IOC: 'VEN', ISO3: 'VEN', ISO2: 'VE'}; break;
    case 'VIE' : return { countryName: 'Vietnam', IOC: 'VIE', ISO3: 'VNM', ISO2: 'VN'}; break;
    case 'YEM' : return { countryName: 'Yemen', IOC: 'YEM', ISO3: 'YEM', ISO2: 'YE'}; break;
    case 'ZAM' : return { countryName: 'Zambia', IOC: 'ZAM', ISO3: 'ZMB', ISO2: 'ZM'}; break;
    case 'ZIM' : return { countryName: 'Zimbabwe', IOC: 'ZIM', ISO3: 'ZWE', ISO2: 'ZW'}; break;
    case 'GBR' : return { countryName: 'United Kingdom', IOC: 'GBR', ISO3: 'GBR', ISO2: 'GB'}; break;
    default: return "Country not found FIFA"; break;
  }

}

exports.convertISO3CountryCode = function (ISO3CountryCode) {

  switch (ISO3CountryCode.toUpperCase()) { 
    case 'AFG' : return { countryCode: 'Afghanistan', IOC: 'AFG', FIFA: 'AFG', ISO2: 'AF'}; break;
    case 'ALB' : return { countryCode: 'Albania', IOC: 'ALB', FIFA: 'ALB', ISO2: 'AL'}; break;
    case 'ALG' : return { countryCode: 'Algeria', IOC: 'ALG', FIFA: 'ALG', ISO2: 'DZ'}; break;
    case 'ASA' : return { countryCode: 'American Samoa', IOC: 'ASA', FIFA: 'ASA', ISO2: 'AS'}; break;
    case 'AND' : return { countryCode: 'Andorra', IOC: 'AND', FIFA: 'AND', ISO2: 'AD'}; break;
    case 'ANG' : return { countryCode: 'Angola', IOC: 'ANG', FIFA: 'ANG', ISO2: 'AO'}; break;
    case 'ANT' : return { countryCode: 'Antigua and Barbuda', IOC: 'ANT', FIFA: 'ATG', ISO2: 'AG'}; break;
    case 'ARG' : return { countryCode: 'Argentina', IOC: 'ARG', FIFA: 'ARG', ISO2: 'AR'}; break;
    case 'ARM' : return { countryCode: 'Armenia', IOC: 'ARM', FIFA: 'ARM', ISO2: 'AM'}; break;
    case 'ARU' : return { countryCode: 'Aruba', IOC: 'ARU', FIFA: 'ARU', ISO2: 'AW'}; break;
    case 'AUS' : return { countryCode: 'Australia', IOC: 'AUS', FIFA: 'AUS', ISO2: 'AU'}; break;
    case 'AUT' : return { countryCode: 'Austria', IOC: 'AUT', FIFA: 'AUT', ISO2: 'AT'}; break;
    case 'AZE' : return { countryCode: 'Azerbaijan', IOC: 'AZE', FIFA: 'AZE', ISO2: 'AZ'}; break;
    case 'BAH' : return { countryCode: 'The Bahamas', IOC: 'BAH', FIFA: 'BAH', ISO2: 'BS'}; break;
    case 'BRN' : return { countryCode: 'Bahrain', IOC: 'BRN', FIFA: 'BHR', ISO2: 'BH'}; break;
    case 'BAN' : return { countryCode: 'Bangladesh', IOC: 'BAN', FIFA: 'BAN', ISO2: 'BD'}; break;
    case 'BAR' : return { countryCode: 'Barbados', IOC: 'BAR', FIFA: 'BRB', ISO2: 'BB'}; break;
    case 'BLR' : return { countryCode: 'Belarus', IOC: 'BLR', FIFA: 'BLR', ISO2: 'BY'}; break;
    case 'BEL' : return { countryCode: 'Belgium', IOC: 'BEL', FIFA: 'BEL', ISO2: 'BE'}; break;
    case 'BIZ' : return { countryCode: 'Belize', IOC: 'BIZ', FIFA: 'BLZ', ISO2: 'BZ'}; break;
    case 'BEN' : return { countryCode: 'Benin', IOC: 'BEN', FIFA: 'BEN', ISO2: 'BJ'}; break;
    case 'BER' : return { countryCode: 'Bermuda', IOC: 'BER', FIFA: 'BER', ISO2: 'BM'}; break;
    case 'BHU' : return { countryCode: 'Bhutan', IOC: 'BHU', FIFA: 'BHU', ISO2: 'BT'}; break;
    case 'BOL' : return { countryCode: 'Bolivia', IOC: 'BOL', FIFA: 'BOL', ISO2: 'BO'}; break;
    case 'BIH' : return { countryCode: 'Bosnia and Herzegovina', IOC: 'BIH', FIFA: 'BIH', ISO2: 'BA'}; break;
    case 'BOT' : return { countryCode: 'Botswana', IOC: 'BOT', FIFA: 'BOT', ISO2: 'BW'}; break;
    case 'BRA' : return { countryCode: 'Brazil', IOC: 'BRA', FIFA: 'BRA', ISO2: 'BR'}; break;
    case 'IVB' : return { countryCode: 'British Virgin Islands', IOC: 'IVB', FIFA: 'VGB', ISO2: 'VG'}; break;
    case 'BRU' : return { countryCode: 'Brunei', IOC: 'BRU', FIFA: 'BRU', ISO2: 'BN'}; break;
    case 'BUL' : return { countryCode: 'Bulgaria', IOC: 'BUL', FIFA: 'BUL', ISO2: 'BG'}; break;
    case 'BUR' : return { countryCode: 'Burkina Faso', IOC: 'BUR', FIFA: 'BFA', ISO2: 'BF'}; break;
    case 'BDI' : return { countryCode: 'Burundi', IOC: 'BDI', FIFA: 'BDI', ISO2: 'BI'}; break;
    case 'CAM' : return { countryCode: 'Cambodia', IOC: 'CAM', FIFA: 'CAM', ISO2: 'KH'}; break;
    case 'CMR' : return { countryCode: 'Cameroon', IOC: 'CMR', FIFA: 'CMR', ISO2: 'CM'}; break;
    case 'CAN' : return { countryCode: 'Canada', IOC: 'CAN', FIFA: 'CAN', ISO2: 'CA'}; break;
    case 'CPV' : return { countryCode: 'Cape Verde', IOC: 'CPV', FIFA: 'CPV', ISO2: 'CV'}; break;
    case 'CAY' : return { countryCode: 'Cayman Islands', IOC: 'CAY', FIFA: 'CAY', ISO2: 'KY'}; break;
    case 'CAF' : return { countryCode: 'Central African Republic', IOC: 'CAF', FIFA: 'CTA', ISO2: 'CF'}; break;
    case 'CHA' : return { countryCode: 'Chad', IOC: 'CHA', FIFA: 'CHA', ISO2: 'TD'}; break;
    case 'CHI' : return { countryCode: 'Chile', IOC: 'CHI', FIFA: 'CHI', ISO2: 'CL'}; break;
    case 'CHN' : return { countryCode: 'China', IOC: 'CHN', FIFA: 'CHN', ISO2: 'CN'}; break;
    case 'COL' : return { countryCode: 'Colombia', IOC: 'COL', FIFA: 'COL', ISO2: 'CO'}; break;
    case 'COM' : return { countryCode: 'Comoros', IOC: 'COM', FIFA: 'COM', ISO2: 'KM'}; break;
    case 'COD' : return { countryCode: 'Democratic Republic of Congo', IOC: 'COD', FIFA: 'COD', ISO2: 'CD'}; break;
    case 'CGO' : return { countryCode: 'Republic of Congo', IOC: 'CGO', FIFA: 'CGO', ISO2: 'CG'}; break;
    case 'COK' : return { countryCode: 'Cook Islands', IOC: 'COK', FIFA: 'COK', ISO2: 'CK'}; break;
    case 'CRC' : return { countryCode: 'Costa Rica', IOC: 'CRC', FIFA: 'CRC', ISO2: 'CR'}; break;
    case 'CIV' : return { countryCode: "Côte d'Ivoire", IOC: 'CIV', FIFA: 'CIV', ISO2: 'CI'}; break;
    case 'CRO' : return { countryCode: 'Croatia', IOC: 'CRO', FIFA: 'CRO', ISO2: 'HR'}; break;
    case 'CUB' : return { countryCode: 'Cuba', IOC: 'CUB', FIFA: 'CUB', ISO2: 'CU'}; break;
    case 'CYP' : return { countryCode: 'Cyprus', IOC: 'CYP', FIFA: 'CYP', ISO2: 'CY'}; break;
    case 'CZE' : return { countryCode: 'Czech Republic', IOC: 'CZE', FIFA: 'CZE', ISO2: 'CZ'}; break;
    case 'DEN' : return { countryCode: 'Denmark', IOC: 'DEN', FIFA: 'DEN', ISO2: 'DK'}; break;
    case 'DJI' : return { countryCode: 'Djibouti', IOC: 'DJI', FIFA: 'DJI', ISO2: 'DJ'}; break;
    case 'DMA' : return { countryCode: 'Dominica', IOC: 'DMA', FIFA: 'DMA', ISO2: 'DM'}; break;
    case 'DOM' : return { countryCode: 'Dominican Republic', IOC: 'DOM', FIFA: 'DOM', ISO2: 'DO'}; break;
    case 'ECU' : return { countryCode: 'Ecuador', IOC: 'ECU', FIFA: 'ECU', ISO2: 'EC'}; break;
    case 'EGY' : return { countryCode: 'Egypt', IOC: 'EGY', FIFA: 'EGY', ISO2: 'EG'}; break;
    case 'ESA' : return { countryCode: 'El Salvador', IOC: 'ESA', FIFA: 'SLV', ISO2: 'SV'}; break;
    case 'GEQ' : return { countryCode: 'Equatorial Guinea', IOC: 'GEQ', FIFA: 'EQG', ISO2: 'GQ'}; break;
    case 'ERI' : return { countryCode: 'Eritrea', IOC: 'ERI', FIFA: 'ERI', ISO2: 'ER'}; break;
    case 'EST' : return { countryCode: 'Estonia', IOC: 'EST', FIFA: 'EST', ISO2: 'EE'}; break;
    case 'ETH' : return { countryCode: 'Ethiopia', IOC: 'ETH', FIFA: 'ETH', ISO2: 'ET'}; break;
    case 'FIJ' : return { countryCode: 'Fiji', IOC: 'FIJ', FIFA: 'FIJ', ISO2: 'FJ'}; break;
    case 'FIN' : return { countryCode: 'Finland', IOC: 'FIN', FIFA: 'FIN', ISO2: 'FI'}; break;
    case 'FRA' : return { countryCode: 'France', IOC: 'FRA', FIFA: 'FRA', ISO2: 'FR'}; break;
    case 'FPN' : return { countryCode: 'French Polynesia', IOC: 'FPN', FIFA: 'TAH', ISO2: 'PF'}; break;
    case 'GAB' : return { countryCode: 'Gabon', IOC: 'GAB', FIFA: 'GAB', ISO2: 'GA'}; break;
    case 'GAM' : return { countryCode: 'The Gambia', IOC: 'GAM', FIFA: 'GAM', ISO2: 'GM'}; break;
    case 'GEO' : return { countryCode: 'Georgia', IOC: 'GEO', FIFA: 'GEO', ISO2: 'GE'}; break;
    case 'GER' : return { countryCode: 'Germany', IOC: 'GER', FIFA: 'GER', ISO2: 'DE'}; break;
    case 'GHA' : return { countryCode: 'Ghana', IOC: 'GHA', FIFA: 'GHA', ISO2: 'GH'}; break;
    case 'GRE' : return { countryCode: 'Greece', IOC: 'GRE', FIFA: 'GRE', ISO2: 'GR'}; break;
    case 'GRN' : return { countryCode: 'Grenada', IOC: 'GRN', FIFA: 'GRN', ISO2: 'GD'}; break;
    case 'GUM' : return { countryCode: 'Guam', IOC: 'GUM', FIFA: 'GUM', ISO2: 'GU'}; break;
    case 'GUA' : return { countryCode: 'Guatemala', IOC: 'GUA', FIFA: 'GUA', ISO2: 'GT'}; break;
    case 'GUI' : return { countryCode: 'Guinea', IOC: 'GUI', FIFA: 'GUI', ISO2: 'GN'}; break;
    case 'GBS' : return { countryCode: 'Guinea-Bissau', IOC: 'GBS', FIFA: 'GNB', ISO2: 'GW'}; break;
    case 'GUY' : return { countryCode: 'Guyana', IOC: 'GUY', FIFA: 'GUY', ISO2: 'GY'}; break;
    case 'HAI' : return { countryCode: 'Haiti', IOC: 'HAI', FIFA: 'HAI', ISO2: 'HT'}; break;
    case 'HON' : return { countryCode: 'Honduras', IOC: 'HON', FIFA: 'HON', ISO2: 'HN'}; break;
    case 'HKG' : return { countryCode: 'Hong Kong', IOC: 'HKG', FIFA: 'HKG', ISO2: 'HK'}; break;
    case 'HUN' : return { countryCode: 'Hungary', IOC: 'HUN', FIFA: 'HUN', ISO2: 'HU'}; break;
    case 'ISL' : return { countryCode: 'Iceland', IOC: 'ISL', FIFA: 'ISL', ISO2: 'IS'}; break;
    case 'IND' : return { countryCode: 'India', IOC: 'IND', FIFA: 'IND', ISO2: 'IN'}; break;
    case 'INA' : return { countryCode: 'Indonesia', IOC: 'INA', FIFA: 'IDN', ISO2: 'ID'}; break;
    case 'IRI' : return { countryCode: 'Iran', IOC: 'IRI', FIFA: 'IRN', ISO2: 'IR'}; break;
    case 'IRQ' : return { countryCode: 'Iraq', IOC: 'IRQ', FIFA: 'IRQ', ISO2: 'IQ'}; break;
    case 'IRL' : return { countryCode: 'Ireland', IOC: 'IRL', FIFA: 'IRL', ISO2: 'IE'}; break;
    case 'ISR' : return { countryCode: 'Israel', IOC: 'ISR', FIFA: 'ISR', ISO2: 'IL'}; break;
    case 'ITA' : return { countryCode: 'Italy', IOC: 'ITA', FIFA: 'ITA', ISO2: 'IT'}; break;
    case 'JAM' : return { countryCode: 'Jamaica', IOC: 'JAM', FIFA: 'JAM', ISO2: 'JM'}; break;
    case 'JPN' : return { countryCode: 'Japan', IOC: 'JPN', FIFA: 'JPN', ISO2: 'JP'}; break;
    case 'JOR' : return { countryCode: 'Jordan', IOC: 'JOR', FIFA: 'JOR', ISO2: 'JO'}; break;
    case 'KAZ' : return { countryCode: 'Kazakhstan', IOC: 'KAZ', FIFA: 'KAZ', ISO2: 'KZ'}; break;
    case 'KEN' : return { countryCode: 'Kenya', IOC: 'KEN', FIFA: 'KEN', ISO2: 'KE'}; break;
    case 'PRK' : return { countryCode: 'North Korea', IOC: 'PRK', FIFA: 'PRK', ISO2: 'KP'}; break;
    case 'KOR' : return { countryCode: 'South Korea', IOC: 'KOR', FIFA: 'KOR', ISO2: 'KR'}; break;
    case 'KUW' : return { countryCode: 'Kuwait', IOC: 'KUW', FIFA: 'KUW', ISO2: 'KW'}; break;
    case 'KGZ' : return { countryCode: 'Kyrgyzstan', IOC: 'KGZ', FIFA: 'KGZ', ISO2: 'KG'}; break;
    case 'LAO' : return { countryCode: 'Laos', IOC: 'LAO', FIFA: 'LAO', ISO2: 'LA'}; break;
    case 'LAT' : return { countryCode: 'Latvia', IOC: 'LAT', FIFA: 'LVA', ISO2: 'LV'}; break;
    case 'LIB' : return { countryCode: 'Lebanon', IOC: 'LIB', FIFA: 'LBN', ISO2: 'LB'}; break;
    case 'LES' : return { countryCode: 'Lesotho', IOC: 'LES', FIFA: 'LES', ISO2: 'LS'}; break;
    case 'LBR' : return { countryCode: 'Liberia', IOC: 'LBR', FIFA: 'LBR', ISO2: 'LR'}; break;
    case 'LBA' : return { countryCode: 'Libya', IOC: 'LBA', FIFA: 'LBY', ISO2: 'LY'}; break;
    case 'LIE' : return { countryCode: 'Liechtenstein', IOC: 'LIE', FIFA: 'LIE', ISO2: 'LI'}; break;
    case 'LTU' : return { countryCode: 'Lithuania', IOC: 'LTU', FIFA: 'LTU', ISO2: 'LT'}; break;
    case 'LUX' : return { countryCode: 'Luxembourg', IOC: 'LUX', FIFA: 'LUX', ISO2: 'LU'}; break;
    case 'MKD' : return { countryCode: 'Macedonia', IOC: 'MKD', FIFA: 'MKD', ISO2: 'MK'}; break;
    case 'MAD' : return { countryCode: 'Madagascar', IOC: 'MAD', FIFA: 'MAD', ISO2: 'MG'}; break;
    case 'MAW' : return { countryCode: 'Malawi', IOC: 'MAW', FIFA: 'MWI', ISO2: 'MW'}; break;
    case 'MAS' : return { countryCode: 'Malaysia', IOC: 'MAS', FIFA: 'MAS', ISO2: 'MY'}; break;
    case 'MDV' : return { countryCode: 'Maldives', IOC: 'MDV', FIFA: 'MDV', ISO2: 'MV'}; break;
    case 'MLI' : return { countryCode: 'Mali', IOC: 'MLI', FIFA: 'MLI', ISO2: 'ML'}; break;
    case 'MLT' : return { countryCode: 'Malta', IOC: 'MLT', FIFA: 'MLT', ISO2: 'MT'}; break;
    case 'MTN' : return { countryCode: 'Mauritania', IOC: 'MTN', FIFA: 'MTN', ISO2: 'MR'}; break;
    case 'MRI' : return { countryCode: 'Mauritius', IOC: 'MRI', FIFA: 'MRI', ISO2: 'MU'}; break;
    case 'MEX' : return { countryCode: 'Mexico', IOC: 'MEX', FIFA: 'MEX', ISO2: 'MX'}; break;
    case 'MDA' : return { countryCode: 'Moldova', IOC: 'MDA', FIFA: 'MDA', ISO2: 'MD'}; break;
    case 'MGL' : return { countryCode: 'Mongolia', IOC: 'MGL', FIFA: 'MNG', ISO2: 'MN'}; break;
    case 'MNE' : return { countryCode: 'Montenegro', IOC: 'MNE', FIFA: 'MNE', ISO2: 'ME'}; break;
    case 'MAR' : return { countryCode: 'Morocco', IOC: 'MAR', FIFA: 'MAR', ISO2: 'MA'}; break;
    case 'MOZ' : return { countryCode: 'Mozambique', IOC: 'MOZ', FIFA: 'MOZ', ISO2: 'MZ'}; break;
    case 'MYA' : return { countryCode: 'Myanmar', IOC: 'MYA', FIFA: 'MYA', ISO2: 'MM'}; break;
    case 'NAM' : return { countryCode: 'Namibia', IOC: 'NAM', FIFA: 'NAM', ISO2: 'NA'}; break;
    case 'NEP' : return { countryCode: 'Nepal', IOC: 'NEP', FIFA: 'NEP', ISO2: 'NP'}; break;
    case 'NED' : return { countryCode: 'Netherlands', IOC: 'NED', FIFA: 'NED', ISO2: 'NL'}; break;
    case 'NZL' : return { countryCode: 'New Zealand', IOC: 'NZL', FIFA: 'NZL', ISO2: 'NZ'}; break;
    case 'NCA' : return { countryCode: 'Nicaragua', IOC: 'NCA', FIFA: 'NCA', ISO2: 'NI'}; break;
    case 'NIG' : return { countryCode: 'Niger', IOC: 'NIG', FIFA: 'NIG', ISO2: 'NE'}; break;
    case 'NGR' : return { countryCode: 'Nigeria', IOC: 'NGR', FIFA: 'NGA', ISO2: 'NG'}; break;
    case 'NOR' : return { countryCode: 'Norway', IOC: 'NOR', FIFA: 'NOR', ISO2: 'NO'}; break;
    case 'OMA' : return { countryCode: 'Oman', IOC: 'OMA', FIFA: 'OMA', ISO2: 'OM'}; break;
    case 'PAK' : return { countryCode: 'Pakistan', IOC: 'PAK', FIFA: 'PAK', ISO2: 'PK'}; break;
    case 'PLE' : return { countryCode: 'Palestinian Authority', IOC: 'PLE', FIFA: 'PLE', ISO2: 'PS'}; break;
    case 'PAN' : return { countryCode: 'Panama', IOC: 'PAN', FIFA: 'PAN', ISO2: 'PA'}; break;
    case 'PNG' : return { countryCode: 'Papua New Guinea', IOC: 'PNG', FIFA: 'PNG', ISO2: 'PG'}; break;
    case 'PAR' : return { countryCode: 'Paraguay', IOC: 'PAR', FIFA: 'PAR', ISO2: 'PY'}; break;
    case 'PER' : return { countryCode: 'Peru', IOC: 'PER', FIFA: 'PER', ISO2: 'PE'}; break;
    case 'PHI' : return { countryCode: 'Philippines', IOC: 'PHI', FIFA: 'PHI', ISO2: 'PH'}; break;
    case 'POL' : return { countryCode: 'Poland', IOC: 'POL', FIFA: 'POL', ISO2: 'PL'}; break;
    case 'POR' : return { countryCode: 'Portugal', IOC: 'POR', FIFA: 'POR', ISO2: 'PT'}; break;
    case 'PUR' : return { countryCode: 'Puerto Rico', IOC: 'PUR', FIFA: 'PUR', ISO2: 'PR'}; break;
    case 'QAT' : return { countryCode: 'Qatar', IOC: 'QAT', FIFA: 'QAT', ISO2: 'QA'}; break;
    case 'ROU' : return { countryCode: 'Romania', IOC: 'ROU', FIFA: 'ROU', ISO2: 'RO'}; break;
    case 'RUS' : return { countryCode: 'Russia', IOC: 'RUS', FIFA: 'RUS', ISO2: 'RU'}; break;
    case 'RWA' : return { countryCode: 'Rwanda', IOC: 'RWA', FIFA: 'RWA', ISO2: 'RW'}; break;
    case 'SKN' : return { countryCode: 'Saint Kitts and Nevis', IOC: 'SKN', FIFA: 'SKN', ISO2: 'KN'}; break;
    case 'LCA' : return { countryCode: 'Saint Lucia', IOC: 'LCA', FIFA: 'LCA', ISO2: 'LC'}; break;
    case 'VIN' : return { countryCode: 'Saint Vincent and the Grenadines', IOC: 'VIN', FIFA: 'VIN', ISO2: 'VC'}; break;
    case 'SAM' : return { countryCode: 'Samoa', IOC: 'SAM', FIFA: 'SAM', ISO2: 'WS'}; break;
    case 'SMR' : return { countryCode: 'San Marino', IOC: 'SMR', FIFA: 'SMR', ISO2: 'SM'}; break;
    case 'STP' : return { countryCode: 'São Tomé and Príncipe', IOC: 'STP', FIFA: 'STP', ISO2: 'ST'}; break;
    case 'KSA' : return { countryCode: 'Saudi Arabia', IOC: 'KSA', FIFA: 'KSA', ISO2: 'SA'}; break;
    case 'SEN' : return { countryCode: 'Senegal', IOC: 'SEN', FIFA: 'SEN', ISO2: 'SN'}; break;
    case 'SRB' : return { countryCode: 'Serbia', IOC: 'SRB', FIFA: 'SRB', ISO2: 'RS'}; break;
    case 'SEY' : return { countryCode: 'Seychelles', IOC: 'SEY', FIFA: 'SEY', ISO2: 'SC'}; break;
    case 'SLE' : return { countryCode: 'Sierra Leone', IOC: 'SLE', FIFA: 'SLE', ISO2: 'SL'}; break;
    case 'SGP' : return { countryCode: 'Singapore', IOC: 'SGP', FIFA: 'SIN', ISO2: 'SG'}; break;
    case 'SVK' : return { countryCode: 'Slovakia', IOC: 'SVK', FIFA: 'SVK', ISO2: 'SK'}; break;
    case 'SLO' : return { countryCode: 'Slovenia', IOC: 'SLO', FIFA: 'SVN', ISO2: 'SI'}; break;
    case 'SOL' : return { countryCode: 'Solomon Islands', IOC: 'SOL', FIFA: 'SOL', ISO2: 'SB'}; break;
    case 'SOM' : return { countryCode: 'Somalia', IOC: 'SOM', FIFA: 'SOM', ISO2: 'SO'}; break;
    case 'RSA' : return { countryCode: 'South Africa', IOC: 'RSA', FIFA: 'RSA', ISO2: 'ZA'}; break;
    case 'ESP' : return { countryCode: 'Spain', IOC: 'ESP', FIFA: 'ESP', ISO2: 'ES'}; break;
    case 'SRI' : return { countryCode: 'Sri Lanka', IOC: 'SRI', FIFA: 'SRI', ISO2: 'LK'}; break;
    case 'SUD' : return { countryCode: 'Sudan', IOC: 'SUD', FIFA: 'SDN', ISO2: 'SD'}; break;
    case 'SUR' : return { countryCode: 'Suriname', IOC: 'SUR', FIFA: 'SUR', ISO2: 'SR'}; break;
    case 'SWZ' : return { countryCode: 'Eswatini', IOC: 'SWZ', FIFA: 'SWZ', ISO2: 'SZ'}; break;
    case 'SWE' : return { countryCode: 'Sweden', IOC: 'SWE', FIFA: 'SWE', ISO2: 'SE'}; break;
    case 'SUI' : return { countryCode: 'Switzerland', IOC: 'SUI', FIFA: 'SUI', ISO2: 'CH'}; break;
    case 'SYR' : return { countryCode: 'Syria', IOC: 'SYR', FIFA: 'SYR', ISO2: 'SY'}; break;
    case 'TPE' : return { countryCode: 'Taiwan', IOC: 'TPE', FIFA: 'TPE', ISO2: 'TW'}; break;
    case 'TJK' : return { countryCode: 'Tajikistan', IOC: 'TJK', FIFA: 'TJK', ISO2: 'TJ'}; break;
    case 'TAN' : return { countryCode: 'Tanzania', IOC: 'TAN', FIFA: 'TAN', ISO2: 'TZ'}; break;
    case 'THA' : return { countryCode: 'Thailand', IOC: 'THA', FIFA: 'THA', ISO2: 'TH'}; break;
    case 'TLS' : return { countryCode: 'Timor-Leste', IOC: 'TLS', FIFA: 'TLS', ISO2: 'TL'}; break;
    case 'TOG' : return { countryCode: 'Togo', IOC: 'TOG', FIFA: 'TOG', ISO2: 'TG'}; break;
    case 'TGA' : return { countryCode: 'Tonga', IOC: 'TGA', FIFA: 'TGA', ISO2: 'TO'}; break;
    case 'TTO' : return { countryCode: 'Trinidad and Tobago', IOC: 'TTO', FIFA: 'TRI', ISO2: 'TT'}; break;
    case 'TUN' : return { countryCode: 'Tunisia', IOC: 'TUN', FIFA: 'TUN', ISO2: 'TN'}; break;
    case 'TUR' : return { countryCode: 'Turkey', IOC: 'TUR', FIFA: 'TUR', ISO2: 'TR'}; break;
    case 'TKM' : return { countryCode: 'Turkmenistan', IOC: 'TKM', FIFA: 'TKM', ISO2: 'TM'}; break;
    case 'TCA' : return { countryCode: 'Turks and Caicos Islands', IOC: 'TCA', FIFA: 'TCA', ISO2: 'TC'}; break;
    case 'UGA' : return { countryCode: 'Uganda', IOC: 'UGA', FIFA: 'UGA', ISO2: 'UG'}; break;
    case 'UKR' : return { countryCode: 'Ukraine', IOC: 'UKR', FIFA: 'UKR', ISO2: 'UA'}; break;
    case 'UAE' : return { countryCode: 'United Arab Emirates', IOC: 'UAE', FIFA: 'UAE', ISO2: 'AE'}; break;
    case 'USA' : return { countryCode: 'United States', IOC: 'USA', FIFA: 'USA', ISO2: 'US'}; break;
    case 'ISV' : return { countryCode: 'United States Virgin Islands', IOC: 'ISV', FIFA: 'VIR', ISO2: 'VI'}; break;
    case 'URU' : return { countryCode: 'Uruguay', IOC: 'URU', FIFA: 'URU', ISO2: 'UY'}; break;
    case 'UZB' : return { countryCode: 'Uzbekistan', IOC: 'UZB', FIFA: 'UZB', ISO2: 'UZ'}; break;
    case 'VAN' : return { countryCode: 'Vanuatu', IOC: 'VAN', FIFA: 'VAN', ISO2: 'VU'}; break;
    case 'VEN' : return { countryCode: 'Venezuela', IOC: 'VEN', FIFA: 'VEN', ISO2: 'VE'}; break;
    case 'VIE' : return { countryCode: 'Vietnam', IOC: 'VIE', FIFA: 'VIE', ISO2: 'VN'}; break;
    case 'YEM' : return { countryCode: 'Yemen', IOC: 'YEM', FIFA: 'YEM', ISO2: 'YE'}; break;
    case 'ZAM' : return { countryCode: 'Zambia', IOC: 'ZAM', FIFA: 'ZAM', ISO2: 'ZM'}; break;
    case 'ZIM' : return { countryCode: 'Zimbabwe', IOC: 'ZIM', FIFA: 'ZIM', ISO2: 'ZW'}; break;
    case 'GBR' : return { countryCode: 'United Kingdom', IOC: 'GBR', FIFA: 'GBR', ISO2: 'GB'}; break;
    default: return "Country not found"; break;
  }

}

exports.convertISO2CountryCode = function convertISO2CountryCode (ISO2CountryCode) {

  switch (ISO2CountryCode.toUpperCase()) { 
    case 'AF' : return { countryName: 'Afghanistan', IOC: 'AFG', FIFA: 'AFG', ISO3: 'AFG'}; break;
    case 'AL' : return { countryName: 'Albania', IOC: 'ALB', FIFA: 'ALB', ISO3: 'ALB'}; break;
    case 'DZ' : return { countryName: 'Algeria', IOC: 'ALG', FIFA: 'ALG', ISO3: 'DZA'}; break;
    case 'AS' : return { countryName: 'American Samoa', IOC: 'ASA', FIFA: 'ASA', ISO3: 'ASM'}; break;
    case 'AD' : return { countryName: 'Andorra', IOC: 'AND', FIFA: 'AND', ISO3: 'AND'}; break;
    case 'AO' : return { countryName: 'Angola', IOC: 'ANG', FIFA: 'ANG', ISO3: 'AGO'}; break;
    case 'AG' : return { countryName: 'Antigua and Barbuda', IOC: 'ANT', FIFA: 'ATG', ISO3: 'ATG'}; break;
    case 'AR' : return { countryName: 'Argentina', IOC: 'ARG', FIFA: 'ARG', ISO3: 'ARG'}; break;
    case 'AM' : return { countryName: 'Armenia', IOC: 'ARM', FIFA: 'ARM', ISO3: 'ARM'}; break;
    case 'AW' : return { countryName: 'Aruba', IOC: 'ARU', FIFA: 'ARU', ISO3: 'ABW'}; break;
    case 'AU' : return { countryName: 'Australia', IOC: 'AUS', FIFA: 'AUS', ISO3: 'AUS'}; break;
    case 'AT' : return { countryName: 'Austria', IOC: 'AUT', FIFA: 'AUT', ISO3: 'AUT'}; break;
    case 'AZ' : return { countryName: 'Azerbaijan', IOC: 'AZE', FIFA: 'AZE', ISO3: 'AZE'}; break;
    case 'BS' : return { countryName: 'The Bahamas', IOC: 'BAH', FIFA: 'BAH', ISO3: 'BHS'}; break;
    case 'BH' : return { countryName: 'Bahrain', IOC: 'BRN', FIFA: 'BHR', ISO3: 'BHR'}; break;
    case 'BD' : return { countryName: 'Bangladesh', IOC: 'BAN', FIFA: 'BAN', ISO3: 'BGD'}; break;
    case 'BB' : return { countryName: 'Barbados', IOC: 'BAR', FIFA: 'BRB', ISO3: 'BRB'}; break;
    case 'BY' : return { countryName: 'Belarus', IOC: 'BLR', FIFA: 'BLR', ISO3: 'BLR'}; break;
    case 'BE' : return { countryName: 'Belgium', IOC: 'BEL', FIFA: 'BEL', ISO3: 'BEL'}; break;
    case 'BZ' : return { countryName: 'Belize', IOC: 'BIZ', FIFA: 'BLZ', ISO3: 'BLZ'}; break;
    case 'BJ' : return { countryName: 'Benin', IOC: 'BEN', FIFA: 'BEN', ISO3: 'BEN'}; break;
    case 'BM' : return { countryName: 'Bermuda', IOC: 'BER', FIFA: 'BER', ISO3: 'BMU'}; break;
    case 'BT' : return { countryName: 'Bhutan', IOC: 'BHU', FIFA: 'BHU', ISO3: 'BTN'}; break;
    case 'BO' : return { countryName: 'Bolivia', IOC: 'BOL', FIFA: 'BOL', ISO3: 'BOL'}; break;
    case 'BA' : return { countryName: 'Bosnia and Herzegovina', IOC: 'BIH', FIFA: 'BIH', ISO3: 'BIH'}; break;
    case 'BW' : return { countryName: 'Botswana', IOC: 'BOT', FIFA: 'BOT', ISO3: 'BWA'}; break;
    case 'BR' : return { countryName: 'Brazil', IOC: 'BRA', FIFA: 'BRA', ISO3: 'BRA'}; break;
    case 'VG' : return { countryName: 'British Virgin Islands', IOC: 'IVB', FIFA: 'VGB', ISO3: 'VGB'}; break;
    case 'BN' : return { countryName: 'Brunei', IOC: 'BRU', FIFA: 'BRU', ISO3: 'BRN'}; break;
    case 'BG' : return { countryName: 'Bulgaria', IOC: 'BUL', FIFA: 'BUL', ISO3: 'BGR'}; break;
    case 'BF' : return { countryName: 'Burkina Faso', IOC: 'BUR', FIFA: 'BFA', ISO3: 'BFA'}; break;
    case 'BI' : return { countryName: 'Burundi', IOC: 'BDI', FIFA: 'BDI', ISO3: 'BDI'}; break;
    case 'KH' : return { countryName: 'Cambodia', IOC: 'CAM', FIFA: 'CAM', ISO3: 'KHM'}; break;
    case 'CM' : return { countryName: 'Cameroon', IOC: 'CMR', FIFA: 'CMR', ISO3: 'CMR'}; break;
    case 'CA' : return { countryName: 'Canada', IOC: 'CAN', FIFA: 'CAN', ISO3: 'CAN'}; break;
    case 'CV' : return { countryName: 'Cape Verde', IOC: 'CPV', FIFA: 'CPV', ISO3: 'CPV'}; break;
    case 'KY' : return { countryName: 'Cayman Islands', IOC: 'CAY', FIFA: 'CAY', ISO3: 'CYM'}; break;
    case 'CF' : return { countryName: 'Central African Republic', IOC: 'CAF', FIFA: 'CTA', ISO3: 'CAF'}; break;
    case 'TD' : return { countryName: 'Chad', IOC: 'CHA', FIFA: 'CHA', ISO3: 'TCD'}; break;
    case 'CL' : return { countryName: 'Chile', IOC: 'CHI', FIFA: 'CHI', ISO3: 'CHL'}; break;
    case 'CN' : return { countryName: 'China', IOC: 'CHN', FIFA: 'CHN', ISO3: 'CHN'}; break;
    case 'CO' : return { countryName: 'Colombia', IOC: 'COL', FIFA: 'COL', ISO3: 'COL'}; break;
    case 'KM' : return { countryName: 'Comoros', IOC: 'COM', FIFA: 'COM', ISO3: 'COM'}; break;
    case 'CD' : return { countryName: 'Democratic Republic of Congo', IOC: 'COD', FIFA: 'COD', ISO3: 'COD'}; break;
    case 'CG' : return { countryName: 'Republic of Congo', IOC: 'CGO', FIFA: 'CGO', ISO3: 'COG'}; break;
    case 'CK' : return { countryName: 'Cook Islands', IOC: 'COK', FIFA: 'COK', ISO3: 'COK'}; break;
    case 'CR' : return { countryName: 'Costa Rica', IOC: 'CRC', FIFA: 'CRC', ISO3: 'CRI'}; break;
    case 'CI' : return { countryName: "Côte d'Ivoire", IOC: 'CIV', FIFA: 'CIV', ISO3: 'CIV'}; break;
    case 'HR' : return { countryName: 'Croatia', IOC: 'CRO', FIFA: 'CRO', ISO3: 'HRV'}; break;
    case 'CU' : return { countryName: 'Cuba', IOC: 'CUB', FIFA: 'CUB', ISO3: 'CUB'}; break;
    case 'CY' : return { countryName: 'Cyprus', IOC: 'CYP', FIFA: 'CYP', ISO3: 'CYP'}; break;
    case 'CZ' : return { countryName: 'Czech Republic', IOC: 'CZE', FIFA: 'CZE', ISO3: 'CZE'}; break;
    case 'DK' : return { countryName: 'Denmark', IOC: 'DEN', FIFA: 'DEN', ISO3: 'DNK'}; break;
    case 'DJ' : return { countryName: 'Djibouti', IOC: 'DJI', FIFA: 'DJI', ISO3: 'DJI'}; break;
    case 'DM' : return { countryName: 'Dominica', IOC: 'DMA', FIFA: 'DMA', ISO3: 'DMA'}; break;
    case 'DO' : return { countryName: 'Dominican Republic', IOC: 'DOM', FIFA: 'DOM', ISO3: 'DOM'}; break;
    case 'EC' : return { countryName: 'Ecuador', IOC: 'ECU', FIFA: 'ECU', ISO3: 'ECU'}; break;
    case 'EG' : return { countryName: 'Egypt', IOC: 'EGY', FIFA: 'EGY', ISO3: 'EGY'}; break;
    case 'SV' : return { countryName: 'El Salvador', IOC: 'ESA', FIFA: 'SLV', ISO3: 'SLV'}; break;
    case 'GQ' : return { countryName: 'Equatorial Guinea', IOC: 'GEQ', FIFA: 'EQG', ISO3: 'GNQ'}; break;
    case 'ER' : return { countryName: 'Eritrea', IOC: 'ERI', FIFA: 'ERI', ISO3: 'ERI'}; break;
    case 'EE' : return { countryName: 'Estonia', IOC: 'EST', FIFA: 'EST', ISO3: 'EST'}; break;
    case 'ET' : return { countryName: 'Ethiopia', IOC: 'ETH', FIFA: 'ETH', ISO3: 'ETH'}; break;
    case 'FJ' : return { countryName: 'Fiji', IOC: 'FIJ', FIFA: 'FIJ', ISO3: 'FJI'}; break;
    case 'FI' : return { countryName: 'Finland', IOC: 'FIN', FIFA: 'FIN', ISO3: 'FIN'}; break;
    case 'FR' : return { countryName: 'France', IOC: 'FRA', FIFA: 'FRA', ISO3: 'FRA'}; break;
    case 'PF' : return { countryName: 'French Polynesia', IOC: 'FPN', FIFA: 'TAH', ISO3: 'PYF'}; break;
    case 'GA' : return { countryName: 'Gabon', IOC: 'GAB', FIFA: 'GAB', ISO3: 'GAB'}; break;
    case 'GM' : return { countryName: 'The Gambia', IOC: 'GAM', FIFA: 'GAM', ISO3: 'GMB'}; break;
    case 'GE' : return { countryName: 'Georgia', IOC: 'GEO', FIFA: 'GEO', ISO3: 'GEO'}; break;
    case 'DE' : return { countryName: 'Germany', IOC: 'GER', FIFA: 'GER', ISO3: 'DEU'}; break;
    case 'GH' : return { countryName: 'Ghana', IOC: 'GHA', FIFA: 'GHA', ISO3: 'GHA'}; break;
    case 'GR' : return { countryName: 'Greece', IOC: 'GRE', FIFA: 'GRE', ISO3: 'GRC'}; break;
    case 'GD' : return { countryName: 'Grenada', IOC: 'GRN', FIFA: 'GRN', ISO3: 'GRD'}; break;
    case 'GU' : return { countryName: 'Guam', IOC: 'GUM', FIFA: 'GUM', ISO3: 'GUM'}; break;
    case 'GT' : return { countryName: 'Guatemala', IOC: 'GUA', FIFA: 'GUA', ISO3: 'GTM'}; break;
    case 'GN' : return { countryName: 'Guinea', IOC: 'GUI', FIFA: 'GUI', ISO3: 'GIN'}; break;
    case 'GW' : return { countryName: 'Guinea-Bissau', IOC: 'GBS', FIFA: 'GNB', ISO3: 'GNB'}; break;
    case 'GY' : return { countryName: 'Guyana', IOC: 'GUY', FIFA: 'GUY', ISO3: 'GUY'}; break;
    case 'HT' : return { countryName: 'Haiti', IOC: 'HAI', FIFA: 'HAI', ISO3: 'HTI'}; break;
    case 'HN' : return { countryName: 'Honduras', IOC: 'HON', FIFA: 'HON', ISO3: 'HND'}; break;
    case 'HK' : return { countryName: 'Hong Kong', IOC: 'HKG', FIFA: 'HKG', ISO3: 'HKG'}; break;
    case 'HU' : return { countryName: 'Hungary', IOC: 'HUN', FIFA: 'HUN', ISO3: 'HUN'}; break;
    case 'IS' : return { countryName: 'Iceland', IOC: 'ISL', FIFA: 'ISL', ISO3: 'ISL'}; break;
    case 'IN' : return { countryName: 'India', IOC: 'IND', FIFA: 'IND', ISO3: 'IND'}; break;
    case 'ID' : return { countryName: 'Indonesia', IOC: 'INA', FIFA: 'IDN', ISO3: 'IDN'}; break;
    case 'IR' : return { countryName: 'Iran', IOC: 'IRI', FIFA: 'IRN', ISO3: 'IRN'}; break;
    case 'IQ' : return { countryName: 'Iraq', IOC: 'IRQ', FIFA: 'IRQ', ISO3: 'IRQ'}; break;
    case 'IE' : return { countryName: 'Ireland', IOC: 'IRL', FIFA: 'IRL', ISO3: 'IRL'}; break;
    case 'IL' : return { countryName: 'Israel', IOC: 'ISR', FIFA: 'ISR', ISO3: 'ISR'}; break;
    case 'IT' : return { countryName: 'Italy', IOC: 'ITA', FIFA: 'ITA', ISO3: 'ITA'}; break;
    case 'JM' : return { countryName: 'Jamaica', IOC: 'JAM', FIFA: 'JAM', ISO3: 'JAM'}; break;
    case 'JP' : return { countryName: 'Japan', IOC: 'JPN', FIFA: 'JPN', ISO3: 'JPN'}; break;
    case 'JO' : return { countryName: 'Jordan', IOC: 'JOR', FIFA: 'JOR', ISO3: 'JOR'}; break;
    case 'KZ' : return { countryName: 'Kazakhstan', IOC: 'KAZ', FIFA: 'KAZ', ISO3: 'KAZ'}; break;
    case 'KE' : return { countryName: 'Kenya', IOC: 'KEN', FIFA: 'KEN', ISO3: 'KEN'}; break;
    case 'KP' : return { countryName: 'North Korea', IOC: 'PRK', FIFA: 'PRK', ISO3: 'PRK'}; break;
    case 'KR' : return { countryName: 'South Korea', IOC: 'KOR', FIFA: 'KOR', ISO3: 'KOR'}; break;
    case 'KW' : return { countryName: 'Kuwait', IOC: 'KUW', FIFA: 'KUW', ISO3: 'KWT'}; break;
    case 'KG' : return { countryName: 'Kyrgyzstan', IOC: 'KGZ', FIFA: 'KGZ', ISO3: 'KGZ'}; break;
    case 'LA' : return { countryName: 'Laos', IOC: 'LAO', FIFA: 'LAO', ISO3: 'LAO'}; break;
    case 'LV' : return { countryName: 'Latvia', IOC: 'LAT', FIFA: 'LVA', ISO3: 'LVA'}; break;
    case 'LB' : return { countryName: 'Lebanon', IOC: 'LIB', FIFA: 'LBN', ISO3: 'LBN'}; break;
    case 'LS' : return { countryName: 'Lesotho', IOC: 'LES', FIFA: 'LES', ISO3: 'LSO'}; break;
    case 'LR' : return { countryName: 'Liberia', IOC: 'LBR', FIFA: 'LBR', ISO3: 'LBR'}; break;
    case 'LY' : return { countryName: 'Libya', IOC: 'LBA', FIFA: 'LBY', ISO3: 'LBY'}; break;
    case 'LI' : return { countryName: 'Liechtenstein', IOC: 'LIE', FIFA: 'LIE', ISO3: 'LIE'}; break;
    case 'LT' : return { countryName: 'Lithuania', IOC: 'LTU', FIFA: 'LTU', ISO3: 'LTU'}; break;
    case 'LU' : return { countryName: 'Luxembourg', IOC: 'LUX', FIFA: 'LUX', ISO3: 'LUX'}; break;
    case 'MK' : return { countryName: 'Macedonia', IOC: 'MKD', FIFA: 'MKD', ISO3: 'MKD'}; break;
    case 'MG' : return { countryName: 'Madagascar', IOC: 'MAD', FIFA: 'MAD', ISO3: 'MDG'}; break;
    case 'MW' : return { countryName: 'Malawi', IOC: 'MAW', FIFA: 'MWI', ISO3: 'MWI'}; break;
    case 'MY' : return { countryName: 'Malaysia', IOC: 'MAS', FIFA: 'MAS', ISO3: 'MYS'}; break;
    case 'MV' : return { countryName: 'Maldives', IOC: 'MDV', FIFA: 'MDV', ISO3: 'MDV'}; break;
    case 'ML' : return { countryName: 'Mali', IOC: 'MLI', FIFA: 'MLI', ISO3: 'MLI'}; break;
    case 'MT' : return { countryName: 'Malta', IOC: 'MLT', FIFA: 'MLT', ISO3: 'MLT'}; break;
    case 'MR' : return { countryName: 'Mauritania', IOC: 'MTN', FIFA: 'MTN', ISO3: 'MRT'}; break;
    case 'MU' : return { countryName: 'Mauritius', IOC: 'MRI', FIFA: 'MRI', ISO3: 'MUS'}; break;
    case 'MX' : return { countryName: 'Mexico', IOC: 'MEX', FIFA: 'MEX', ISO3: 'MEX'}; break;
    case 'MD' : return { countryName: 'Moldova', IOC: 'MDA', FIFA: 'MDA', ISO3: 'MDA'}; break;
    case 'MN' : return { countryName: 'Mongolia', IOC: 'MGL', FIFA: 'MNG', ISO3: 'MNG'}; break;
    case 'ME' : return { countryName: 'Montenegro', IOC: 'MNE', FIFA: 'MNE', ISO3: 'MNE'}; break;
    case 'MA' : return { countryName: 'Morocco', IOC: 'MAR', FIFA: 'MAR', ISO3: 'MAR'}; break;
    case 'MZ' : return { countryName: 'Mozambique', IOC: 'MOZ', FIFA: 'MOZ', ISO3: 'MOZ'}; break;
    case 'MM' : return { countryName: 'Myanmar', IOC: 'MYA', FIFA: 'MYA', ISO3: 'MMR'}; break;
    case 'NA' : return { countryName: 'Namibia', IOC: 'NAM', FIFA: 'NAM', ISO3: 'NAM'}; break;
    case 'NP' : return { countryName: 'Nepal', IOC: 'NEP', FIFA: 'NEP', ISO3: 'NPL'}; break;
    case 'NL' : return { countryName: 'Netherlands', IOC: 'NED', FIFA: 'NED', ISO3: 'NLD'}; break;
    case 'NZ' : return { countryName: 'New Zealand', IOC: 'NZL', FIFA: 'NZL', ISO3: 'NZL'}; break;
    case 'NI' : return { countryName: 'Nicaragua', IOC: 'NCA', FIFA: 'NCA', ISO3: 'NIC'}; break;
    case 'NE' : return { countryName: 'Niger', IOC: 'NIG', FIFA: 'NIG', ISO3: 'NER'}; break;
    case 'NG' : return { countryName: 'Nigeria', IOC: 'NGR', FIFA: 'NGA', ISO3: 'NGA'}; break;
    case 'NO' : return { countryName: 'Norway', IOC: 'NOR', FIFA: 'NOR', ISO3: 'NOR'}; break;
    case 'OM' : return { countryName: 'Oman', IOC: 'OMA', FIFA: 'OMA', ISO3: 'OMN'}; break;
    case 'PK' : return { countryName: 'Pakistan', IOC: 'PAK', FIFA: 'PAK', ISO3: 'PAK'}; break;
    case 'PS' : return { countryName: 'Palestinian Authority', IOC: 'PLE', FIFA: 'PLE', ISO3: 'PSE'}; break;
    case 'PA' : return { countryName: 'Panama', IOC: 'PAN', FIFA: 'PAN', ISO3: 'PAN'}; break;
    case 'PG' : return { countryName: 'Papua New Guinea', IOC: 'PNG', FIFA: 'PNG', ISO3: 'PNG'}; break;
    case 'PY' : return { countryName: 'Paraguay', IOC: 'PAR', FIFA: 'PAR', ISO3: 'PRY'}; break;
    case 'PE' : return { countryName: 'Peru', IOC: 'PER', FIFA: 'PER', ISO3: 'PER'}; break;
    case 'PH' : return { countryName: 'Philippines', IOC: 'PHI', FIFA: 'PHI', ISO3: 'PHL'}; break;
    case 'PL' : return { countryName: 'Poland', IOC: 'POL', FIFA: 'POL', ISO3: 'POL'}; break;
    case 'PT' : return { countryName: 'Portugal', IOC: 'POR', FIFA: 'POR', ISO3: 'PRT'}; break;
    case 'PR' : return { countryName: 'Puerto Rico', IOC: 'PUR', FIFA: 'PUR', ISO3: 'PRI'}; break;
    case 'QA' : return { countryName: 'Qatar', IOC: 'QAT', FIFA: 'QAT', ISO3: 'QAT'}; break;
    case 'RO' : return { countryName: 'Romania', IOC: 'ROU', FIFA: 'ROU', ISO3: 'ROU'}; break;
    case 'RU' : return { countryName: 'Russia', IOC: 'RUS', FIFA: 'RUS', ISO3: 'RUS'}; break;
    case 'RW' : return { countryName: 'Rwanda', IOC: 'RWA', FIFA: 'RWA', ISO3: 'RWA'}; break;
    case 'KN' : return { countryName: 'Saint Kitts and Nevis', IOC: 'SKN', FIFA: 'SKN', ISO3: 'KNA'}; break;
    case 'LC' : return { countryName: 'Saint Lucia', IOC: 'LCA', FIFA: 'LCA', ISO3: 'LCA'}; break;
    case 'VC' : return { countryName: 'Saint Vincent and the Grenadines', IOC: 'VIN', FIFA: 'VIN', ISO3: 'VCT'}; break;
    case 'WS' : return { countryName: 'Samoa', IOC: 'SAM', FIFA: 'SAM', ISO3: 'WSM'}; break;
    case 'SM' : return { countryName: 'San Marino', IOC: 'SMR', FIFA: 'SMR', ISO3: 'SMR'}; break;
    case 'ST' : return { countryName: 'São Tomé and Príncipe', IOC: 'STP', FIFA: 'STP', ISO3: 'STP'}; break;
    case 'SA' : return { countryName: 'Saudi Arabia', IOC: 'KSA', FIFA: 'KSA', ISO3: 'SAU'}; break;
    case 'SN' : return { countryName: 'Senegal', IOC: 'SEN', FIFA: 'SEN', ISO3: 'SEN'}; break;
    case 'RS' : return { countryName: 'Serbia', IOC: 'SRB', FIFA: 'SRB', ISO3: 'SRB'}; break;
    case 'SC' : return { countryName: 'Seychelles', IOC: 'SEY', FIFA: 'SEY', ISO3: 'SYC'}; break;
    case 'SL' : return { countryName: 'Sierra Leone', IOC: 'SLE', FIFA: 'SLE', ISO3: 'SLE'}; break;
    case 'SG' : return { countryName: 'Singapore', IOC: 'SGP', FIFA: 'SIN', ISO3: 'SGP'}; break;
    case 'SK' : return { countryName: 'Slovakia', IOC: 'SVK', FIFA: 'SVK', ISO3: 'SVK'}; break;
    case 'SI' : return { countryName: 'Slovenia', IOC: 'SLO', FIFA: 'SVN', ISO3: 'SVN'}; break;
    case 'SB' : return { countryName: 'Solomon Islands', IOC: 'SOL', FIFA: 'SOL', ISO3: 'SLB'}; break;
    case 'SO' : return { countryName: 'Somalia', IOC: 'SOM', FIFA: 'SOM', ISO3: 'SOM'}; break;
    case 'ZA' : return { countryName: 'South Africa', IOC: 'RSA', FIFA: 'RSA', ISO3: 'ZAF'}; break;
    case 'ES' : return { countryName: 'Spain', IOC: 'ESP', FIFA: 'ESP', ISO3: 'ESP'}; break;
    case 'LK' : return { countryName: 'Sri Lanka', IOC: 'SRI', FIFA: 'SRI', ISO3: 'LKA'}; break;
    case 'SD' : return { countryName: 'Sudan', IOC: 'SUD', FIFA: 'SDN', ISO3: 'SDN'}; break;
    case 'SR' : return { countryName: 'Suriname', IOC: 'SUR', FIFA: 'SUR', ISO3: 'SUR'}; break;
    case 'SZ' : return { countryName: 'Eswatini', IOC: 'SWZ', FIFA: 'SWZ', ISO3: 'SWZ'}; break;
    case 'SE' : return { countryName: 'Sweden', IOC: 'SWE', FIFA: 'SWE', ISO3: 'SWE'}; break;
    case 'CH' : return { countryName: 'Switzerland', IOC: 'SUI', FIFA: 'SUI', ISO3: 'CHE'}; break;
    case 'SY' : return { countryName: 'Syria', IOC: 'SYR', FIFA: 'SYR', ISO3: 'SYR'}; break;
    case 'TW' : return { countryName: 'Taiwan', IOC: 'TPE', FIFA: 'TPE', ISO3: 'TWN'}; break;
    case 'TJ' : return { countryName: 'Tajikistan', IOC: 'TJK', FIFA: 'TJK', ISO3: 'TJK'}; break;
    case 'TZ' : return { countryName: 'Tanzania', IOC: 'TAN', FIFA: 'TAN', ISO3: 'TZA'}; break;
    case 'TH' : return { countryName: 'Thailand', IOC: 'THA', FIFA: 'THA', ISO3: 'THA'}; break;
    case 'TL' : return { countryName: 'Timor-Leste', IOC: 'TLS', FIFA: 'TLS', ISO3: 'TLS'}; break;
    case 'TG' : return { countryName: 'Togo', IOC: 'TOG', FIFA: 'TOG', ISO3: 'TGO'}; break;
    case 'TO' : return { countryName: 'Tonga', IOC: 'TGA', FIFA: 'TGA', ISO3: 'TON'}; break;
    case 'TT' : return { countryName: 'Trinidad and Tobago', IOC: 'TTO', FIFA: 'TRI', ISO3: 'TTO'}; break;
    case 'TN' : return { countryName: 'Tunisia', IOC: 'TUN', FIFA: 'TUN', ISO3: 'TUN'}; break;
    case 'TR' : return { countryName: 'Turkey', IOC: 'TUR', FIFA: 'TUR', ISO3: 'TUR'}; break;
    case 'TM' : return { countryName: 'Turkmenistan', IOC: 'TKM', FIFA: 'TKM', ISO3: 'TKM'}; break;
    case 'TC' : return { countryName: 'Turks and Caicos Islands', IOC: 'TCA', FIFA: 'TCA', ISO3: 'TCA'}; break;
    case 'UG' : return { countryName: 'Uganda', IOC: 'UGA', FIFA: 'UGA', ISO3: 'UGA'}; break;
    case 'UA' : return { countryName: 'Ukraine', IOC: 'UKR', FIFA: 'UKR', ISO3: 'UKR'}; break;
    case 'AE' : return { countryName: 'United Arab Emirates', IOC: 'UAE', FIFA: 'UAE', ISO3: 'ARE'}; break;
    case 'US' : return { countryName: 'United States', IOC: 'USA', FIFA: 'USA', ISO3: 'USA'}; break;
    case 'VI' : return { countryName: 'United States Virgin Islands', IOC: 'ISV', FIFA: 'VIR', ISO3: 'VIR'}; break;
    case 'UY' : return { countryName: 'Uruguay', IOC: 'URU', FIFA: 'URU', ISO3: 'URY'}; break;
    case 'UZ' : return { countryName: 'Uzbekistan', IOC: 'UZB', FIFA: 'UZB', ISO3: 'UZB'}; break;
    case 'VU' : return { countryName: 'Vanuatu', IOC: 'VAN', FIFA: 'VAN', ISO3: 'VUT'}; break;
    case 'VE' : return { countryName: 'Venezuela', IOC: 'VEN', FIFA: 'VEN', ISO3: 'VEN'}; break;
    case 'VN' : return { countryName: 'Vietnam', IOC: 'VIE', FIFA: 'VIE', ISO3: 'VNM'}; break;
    case 'YE' : return { countryName: 'Yemen', IOC: 'YEM', FIFA: 'YEM', ISO3: 'YEM'}; break;
    case 'ZM' : return { countryName: 'Zambia', IOC: 'ZAM', FIFA: 'ZAM', ISO3: 'ZMB'}; break;
    case 'ZW' : return { countryName: 'Zimbabwe', IOC: 'ZIM', FIFA: 'ZIM', ISO3: 'ZWE'}; break;
    case 'GB' : return { countryName: 'United Kingdom', IOC: 'GBR', FIFA: 'GBR', ISO3: 'GBR'}; break;
    case 'UK' : return { countryName: 'United Kingdom', IOC: 'GBR', FIFA: 'GBR', ISO3: 'GBR'}; break;
    default: return "Country not found"; break;
  }

}

exports.convertCountryName = function (countryName) {

  switch (countryName.toLowerCase()) {
    case 'afghanistan' : return { IOC: 'AFG', FIFA: 'AFG', ISO3: 'AFG', ISO2: 'AF'}; break;
    case 'albania' : return { IOC: 'ALB', FIFA: 'ALB', ISO3: 'ALB', ISO2: 'AL'}; break;
    case 'algeria' : return { IOC: 'ALG', FIFA: 'ALG', ISO3: 'DZA', ISO2: 'DZ'}; break;
    case 'american samoa' : return { IOC: 'ASA', FIFA: 'ASA', ISO3: 'ASM', ISO2: 'AS'}; break;
    case 'andorra' : return { IOC: 'AND', FIFA: 'AND', ISO3: 'AND', ISO2: 'AD'}; break;
    case 'angola' : return { IOC: 'ANG', FIFA: 'ANG', ISO3: 'AGO', ISO2: 'AO'}; break;
    case 'antigua and barbuda' : return { IOC: 'ANT', FIFA: 'ATG', ISO3: 'ATG', ISO2: 'AG'}; break;
    case 'argentina' : return { IOC: 'ARG', FIFA: 'ARG', ISO3: 'ARG', ISO2: 'AR'}; break;
    case 'armenia' : return { IOC: 'ARM', FIFA: 'ARM', ISO3: 'ARM', ISO2: 'AM'}; break;
    case 'aruba' : return { IOC: 'ARU', FIFA: 'ARU', ISO3: 'ABW', ISO2: 'AW'}; break;
    case 'australia' : return { IOC: 'AUS', FIFA: 'AUS', ISO3: 'AUS', ISO2: 'AU'}; break;
    case 'austria' : return { IOC: 'AUT', FIFA: 'AUT', ISO3: 'AUT', ISO2: 'AT'}; break;
    case 'azerbaijan' : return { IOC: 'AZE', FIFA: 'AZE', ISO3: 'AZE', ISO2: 'AZ'}; break;
    case 'the bahamas' : return { IOC: 'BAH', FIFA: 'BAH', ISO3: 'BHS', ISO2: 'BS'}; break;
    case 'bahrain' : return { IOC: 'BRN', FIFA: 'BHR', ISO3: 'BHR', ISO2: 'BH'}; break;
    case 'bangladesh' : return { IOC: 'BAN', FIFA: 'BAN', ISO3: 'BGD', ISO2: 'BD'}; break;
    case 'barbados' : return { IOC: 'BAR', FIFA: 'BRB', ISO3: 'BRB', ISO2: 'BB'}; break;
    case 'belarus' : return { IOC: 'BLR', FIFA: 'BLR', ISO3: 'BLR', ISO2: 'BY'}; break;
    case 'belgium' : return { IOC: 'BEL', FIFA: 'BEL', ISO3: 'BEL', ISO2: 'BE'}; break;
    case 'belize' : return { IOC: 'BIZ', FIFA: 'BLZ', ISO3: 'BLZ', ISO2: 'BZ'}; break;
    case 'benin' : return { IOC: 'BEN', FIFA: 'BEN', ISO3: 'BEN', ISO2: 'BJ'}; break;
    case 'bermuda' : return { IOC: 'BER', FIFA: 'BER', ISO3: 'BMU', ISO2: 'BM'}; break;
    case 'bhutan' : return { IOC: 'BHU', FIFA: 'BHU', ISO3: 'BTN', ISO2: 'BT'}; break;
    case 'bolivia' : return { IOC: 'BOL', FIFA: 'BOL', ISO3: 'BOL', ISO2: 'BO'}; break;
    case 'bosnia and herzegovina' : return { IOC: 'BIH', FIFA: 'BIH', ISO3: 'BIH', ISO2: 'BA'}; break;
    case 'botswana' : return { IOC: 'BOT', FIFA: 'BOT', ISO3: 'BWA', ISO2: 'BW'}; break;
    case 'brazil' : return { IOC: 'BRA', FIFA: 'BRA', ISO3: 'BRA', ISO2: 'BR'}; break;
    case 'british virgin islands' : return { IOC: 'IVB', FIFA: 'VGB', ISO3: 'VGB', ISO2: 'VG'}; break;
    case 'brunei' : return { IOC: 'BRU', FIFA: 'BRU', ISO3: 'BRN', ISO2: 'BN'}; break;
    case 'bulgaria' : return { IOC: 'BUL', FIFA: 'BUL', ISO3: 'BGR', ISO2: 'BG'}; break;
    case 'burkina faso' : return { IOC: 'BUR', FIFA: 'BFA', ISO3: 'BFA', ISO2: 'BF'}; break;
    case 'burundi' : return { IOC: 'BDI', FIFA: 'BDI', ISO3: 'BDI', ISO2: 'BI'}; break;
    case 'cambodia' : return { IOC: 'CAM', FIFA: 'CAM', ISO3: 'KHM', ISO2: 'KH'}; break;
    case 'cameroon' : return { IOC: 'CMR', FIFA: 'CMR', ISO3: 'CMR', ISO2: 'CM'}; break;
    case 'canada' : return { IOC: 'CAN', FIFA: 'CAN', ISO3: 'CAN', ISO2: 'CA'}; break;
    case 'cape verde' : return { IOC: 'CPV', FIFA: 'CPV', ISO3: 'CPV', ISO2: 'CV'}; break;
    case 'cayman islands' : return { IOC: 'CAY', FIFA: 'CAY', ISO3: 'CYM', ISO2: 'KY'}; break;
    case 'central african republic' : return { IOC: 'CAF', FIFA: 'CTA', ISO3: 'CAF', ISO2: 'CF'}; break;
    case 'chad' : return { IOC: 'CHA', FIFA: 'CHA', ISO3: 'TCD', ISO2: 'TD'}; break;
    case 'chile' : return { IOC: 'CHI', FIFA: 'CHI', ISO3: 'CHL', ISO2: 'CL'}; break;
    case 'china' : return { IOC: 'CHN', FIFA: 'CHN', ISO3: 'CHN', ISO2: 'CN'}; break;
    case 'colombia' : return { IOC: 'COL', FIFA: 'COL', ISO3: 'COL', ISO2: 'CO'}; break;
    case 'comoros' : return { IOC: 'COM', FIFA: 'COM', ISO3: 'COM', ISO2: 'KM'}; break;
    case 'democratic republic of congo' : return { IOC: 'COD', FIFA: 'COD', ISO3: 'COD', ISO2: 'CD'}; break;
    case 'republic of congo' : return { IOC: 'CGO', FIFA: 'CGO', ISO3: 'COG', ISO2: 'CG'}; break;
    case 'cook islands' : return { IOC: 'COK', FIFA: 'COK', ISO3: 'COK', ISO2: 'CK'}; break;
    case 'costa rica' : return { IOC: 'CRC', FIFA: 'CRC', ISO3: 'CRI', ISO2: 'CR'}; break;
    case "côte d'ivoire" : return { IOC: 'CIV', FIFA: 'CIV', ISO3: 'CIV', ISO2: 'CI'}; break;
    case 'croatia' : return { IOC: 'CRO', FIFA: 'CRO', ISO3: 'HRV', ISO2: 'HR'}; break;
    case 'cuba' : return { IOC: 'CUB', FIFA: 'CUB', ISO3: 'CUB', ISO2: 'CU'}; break;
    case 'cyprus' : return { IOC: 'CYP', FIFA: 'CYP', ISO3: 'CYP', ISO2: 'CY'}; break;
    case 'czech republic' : return { IOC: 'CZE', FIFA: 'CZE', ISO3: 'CZE', ISO2: 'CZ'}; break;
    case 'denmark' : return { IOC: 'DEN', FIFA: 'DEN', ISO3: 'DNK', ISO2: 'DK'}; break;
    case 'djibouti' : return { IOC: 'DJI', FIFA: 'DJI', ISO3: 'DJI', ISO2: 'DJ'}; break;
    case 'dominica' : return { IOC: 'DMA', FIFA: 'DMA', ISO3: 'DMA', ISO2: 'DM'}; break;
    case 'dominican republic' : return { IOC: 'DOM', FIFA: 'DOM', ISO3: 'DOM', ISO2: 'DO'}; break;
    case 'ecuador' : return { IOC: 'ECU', FIFA: 'ECU', ISO3: 'ECU', ISO2: 'EC'}; break;
    case 'egypt' : return { IOC: 'EGY', FIFA: 'EGY', ISO3: 'EGY', ISO2: 'EG'}; break;
    case 'el salvador' : return { IOC: 'ESA', FIFA: 'SLV', ISO3: 'SLV', ISO2: 'SV'}; break;
    case 'equatorial guinea' : return { IOC: 'GEQ', FIFA: 'EQG', ISO3: 'GNQ', ISO2: 'GQ'}; break;
    case 'eritrea' : return { IOC: 'ERI', FIFA: 'ERI', ISO3: 'ERI', ISO2: 'ER'}; break;
    case 'estonia' : return { IOC: 'EST', FIFA: 'EST', ISO3: 'EST', ISO2: 'EE'}; break;
    case 'ethiopia' : return { IOC: 'ETH', FIFA: 'ETH', ISO3: 'ETH', ISO2: 'ET'}; break;
    case 'fiji' : return { IOC: 'FIJ', FIFA: 'FIJ', ISO3: 'FJI', ISO2: 'FJ'}; break;
    case 'finland' : return { IOC: 'FIN', FIFA: 'FIN', ISO3: 'FIN', ISO2: 'FI'}; break;
    case 'france' : return { IOC: 'FRA', FIFA: 'FRA', ISO3: 'FRA', ISO2: 'FR'}; break;
    case 'french polynesia' : return { IOC: 'FPN', FIFA: 'TAH', ISO3: 'PYF', ISO2: 'PF'}; break;
    case 'gabon' : return { IOC: 'GAB', FIFA: 'GAB', ISO3: 'GAB', ISO2: 'GA'}; break;
    case 'the gambia' : return { IOC: 'GAM', FIFA: 'GAM', ISO3: 'GMB', ISO2: 'GM'}; break;
    case 'georgia' : return { IOC: 'GEO', FIFA: 'GEO', ISO3: 'GEO', ISO2: 'GE'}; break;
    case 'germany' : return { IOC: 'GER', FIFA: 'GER', ISO3: 'DEU', ISO2: 'DE'}; break;
    case 'ghana' : return { IOC: 'GHA', FIFA: 'GHA', ISO3: 'GHA', ISO2: 'GH'}; break;
    case 'greece' : return { IOC: 'GRE', FIFA: 'GRE', ISO3: 'GRC', ISO2: 'GR'}; break;
    case 'grenada' : return { IOC: 'GRN', FIFA: 'GRN', ISO3: 'GRD', ISO2: 'GD'}; break;
    case 'guam' : return { IOC: 'GUM', FIFA: 'GUM', ISO3: 'GUM', ISO2: 'GU'}; break;
    case 'guatemala' : return { IOC: 'GUA', FIFA: 'GUA', ISO3: 'GTM', ISO2: 'GT'}; break;
    case 'guinea' : return { IOC: 'GUI', FIFA: 'GUI', ISO3: 'GIN', ISO2: 'GN'}; break;
    case 'guinea-bissau' : return { IOC: 'GBS', FIFA: 'GNB', ISO3: 'GNB', ISO2: 'GW'}; break;
    case 'guyana' : return { IOC: 'GUY', FIFA: 'GUY', ISO3: 'GUY', ISO2: 'GY'}; break;
    case 'haiti' : return { IOC: 'HAI', FIFA: 'HAI', ISO3: 'HTI', ISO2: 'HT'}; break;
    case 'honduras' : return { IOC: 'HON', FIFA: 'HON', ISO3: 'HND', ISO2: 'HN'}; break;
    case 'hong kong' : return { IOC: 'HKG', FIFA: 'HKG', ISO3: 'HKG', ISO2: 'HK'}; break;
    case 'hungary' : return { IOC: 'HUN', FIFA: 'HUN', ISO3: 'HUN', ISO2: 'HU'}; break;
    case 'iceland' : return { IOC: 'ISL', FIFA: 'ISL', ISO3: 'ISL', ISO2: 'IS'}; break;
    case 'india' : return { IOC: 'IND', FIFA: 'IND', ISO3: 'IND', ISO2: 'IN'}; break;
    case 'indonesia' : return { IOC: 'INA', FIFA: 'IDN', ISO3: 'IDN', ISO2: 'ID'}; break;
    case 'iran' : return { IOC: 'IRI', FIFA: 'IRN', ISO3: 'IRN', ISO2: 'IR'}; break;
    case 'iraq' : return { IOC: 'IRQ', FIFA: 'IRQ', ISO3: 'IRQ', ISO2: 'IQ'}; break;
    case 'ireland' : return { IOC: 'IRL', FIFA: 'IRL', ISO3: 'IRL', ISO2: 'IE'}; break;
    case 'israel' : return { IOC: 'ISR', FIFA: 'ISR', ISO3: 'ISR', ISO2: 'IL'}; break;
    case 'italy' : return { IOC: 'ITA', FIFA: 'ITA', ISO3: 'ITA', ISO2: 'IT'}; break;
    case 'jamaica' : return { IOC: 'JAM', FIFA: 'JAM', ISO3: 'JAM', ISO2: 'JM'}; break;
    case 'japan' : return { IOC: 'JPN', FIFA: 'JPN', ISO3: 'JPN', ISO2: 'JP'}; break;
    case 'jordan' : return { IOC: 'JOR', FIFA: 'JOR', ISO3: 'JOR', ISO2: 'JO'}; break;
    case 'kazakhstan' : return { IOC: 'KAZ', FIFA: 'KAZ', ISO3: 'KAZ', ISO2: 'KZ'}; break;
    case 'kenya' : return { IOC: 'KEN', FIFA: 'KEN', ISO3: 'KEN', ISO2: 'KE'}; break;
    case 'north korea' : return { IOC: 'PRK', FIFA: 'PRK', ISO3: 'PRK', ISO2: 'KP'}; break;
    case 'south korea' : return { IOC: 'KOR', FIFA: 'KOR', ISO3: 'KOR', ISO2: 'KR'}; break;
    case 'kuwait' : return { IOC: 'KUW', FIFA: 'KUW', ISO3: 'KWT', ISO2: 'KW'}; break;
    case 'kyrgyzstan' : return { IOC: 'KGZ', FIFA: 'KGZ', ISO3: 'KGZ', ISO2: 'KG'}; break;
    case 'laos' : return { IOC: 'LAO', FIFA: 'LAO', ISO3: 'LAO', ISO2: 'LA'}; break;
    case 'latvia' : return { IOC: 'LAT', FIFA: 'LVA', ISO3: 'LVA', ISO2: 'LV'}; break;
    case 'lebanon' : return { IOC: 'LIB', FIFA: 'LBN', ISO3: 'LBN', ISO2: 'LB'}; break;
    case 'lesotho' : return { IOC: 'LES', FIFA: 'LES', ISO3: 'LSO', ISO2: 'LS'}; break;
    case 'liberia' : return { IOC: 'LBR', FIFA: 'LBR', ISO3: 'LBR', ISO2: 'LR'}; break;
    case 'libya' : return { IOC: 'LBA', FIFA: 'LBY', ISO3: 'LBY', ISO2: 'LY'}; break;
    case 'liechtenstein' : return { IOC: 'LIE', FIFA: 'LIE', ISO3: 'LIE', ISO2: 'LI'}; break;
    case 'lithuania' : return { IOC: 'LTU', FIFA: 'LTU', ISO3: 'LTU', ISO2: 'LT'}; break;
    case 'luxembourg' : return { IOC: 'LUX', FIFA: 'LUX', ISO3: 'LUX', ISO2: 'LU'}; break;
    case 'macedonia' : return { IOC: 'MKD', FIFA: 'MKD', ISO3: 'MKD', ISO2: 'MK'}; break;
    case 'madagascar' : return { IOC: 'MAD', FIFA: 'MAD', ISO3: 'MDG', ISO2: 'MG'}; break;
    case 'malawi' : return { IOC: 'MAW', FIFA: 'MWI', ISO3: 'MWI', ISO2: 'MW'}; break;
    case 'malaysia' : return { IOC: 'MAS', FIFA: 'MAS', ISO3: 'MYS', ISO2: 'MY'}; break;
    case 'maldives' : return { IOC: 'MDV', FIFA: 'MDV', ISO3: 'MDV', ISO2: 'MV'}; break;
    case 'mali' : return { IOC: 'MLI', FIFA: 'MLI', ISO3: 'MLI', ISO2: 'ML'}; break;
    case 'malta' : return { IOC: 'MLT', FIFA: 'MLT', ISO3: 'MLT', ISO2: 'MT'}; break;
    case 'mauritania' : return { IOC: 'MTN', FIFA: 'MTN', ISO3: 'MRT', ISO2: 'MR'}; break;
    case 'mauritius' : return { IOC: 'MRI', FIFA: 'MRI', ISO3: 'MUS', ISO2: 'MU'}; break;
    case 'mexico' : return { IOC: 'MEX', FIFA: 'MEX', ISO3: 'MEX', ISO2: 'MX'}; break;
    case 'moldova' : return { IOC: 'MDA', FIFA: 'MDA', ISO3: 'MDA', ISO2: 'MD'}; break;
    case 'mongolia' : return { IOC: 'MGL', FIFA: 'MNG', ISO3: 'MNG', ISO2: 'MN'}; break;
    case 'montenegro' : return { IOC: 'MNE', FIFA: 'MNE', ISO3: 'MNE', ISO2: 'ME'}; break;
    case 'morocco' : return { IOC: 'MAR', FIFA: 'MAR', ISO3: 'MAR', ISO2: 'MA'}; break;
    case 'mozambique' : return { IOC: 'MOZ', FIFA: 'MOZ', ISO3: 'MOZ', ISO2: 'MZ'}; break;
    case 'myanmar' : return { IOC: 'MYA', FIFA: 'MYA', ISO3: 'MMR', ISO2: 'MM'}; break;
    case 'namibia' : return { IOC: 'NAM', FIFA: 'NAM', ISO3: 'NAM', ISO2: 'NA'}; break;
    case 'nepal' : return { IOC: 'NEP', FIFA: 'NEP', ISO3: 'NPL', ISO2: 'NP'}; break;
    case 'netherlands' : return { IOC: 'NED', FIFA: 'NED', ISO3: 'NLD', ISO2: 'NL'}; break;
    case 'new zealand' : return { IOC: 'NZL', FIFA: 'NZL', ISO3: 'NZL', ISO2: 'NZ'}; break;
    case 'nicaragua' : return { IOC: 'NCA', FIFA: 'NCA', ISO3: 'NIC', ISO2: 'NI'}; break;
    case 'niger' : return { IOC: 'NIG', FIFA: 'NIG', ISO3: 'NER', ISO2: 'NE'}; break;
    case 'nigeria' : return { IOC: 'NGR', FIFA: 'NGA', ISO3: 'NGA', ISO2: 'NG'}; break;
    case 'norway' : return { IOC: 'NOR', FIFA: 'NOR', ISO3: 'NOR', ISO2: 'NO'}; break;
    case 'oman' : return { IOC: 'OMA', FIFA: 'OMA', ISO3: 'OMN', ISO2: 'OM'}; break;
    case 'pakistan' : return { IOC: 'PAK', FIFA: 'PAK', ISO3: 'PAK', ISO2: 'PK'}; break;
    case 'palestinian authority' : return { IOC: 'PLE', FIFA: 'PLE', ISO3: 'PSE', ISO2: 'PS'}; break;
    case 'panama' : return { IOC: 'PAN', FIFA: 'PAN', ISO3: 'PAN', ISO2: 'PA'}; break;
    case 'papua new guinea' : return { IOC: 'PNG', FIFA: 'PNG', ISO3: 'PNG', ISO2: 'PG'}; break;
    case 'paraguay' : return { IOC: 'PAR', FIFA: 'PAR', ISO3: 'PRY', ISO2: 'PY'}; break;
    case 'peru' : return { IOC: 'PER', FIFA: 'PER', ISO3: 'PER', ISO2: 'PE'}; break;
    case 'philippines' : return { IOC: 'PHI', FIFA: 'PHI', ISO3: 'PHL', ISO2: 'PH'}; break;
    case 'poland' : return { IOC: 'POL', FIFA: 'POL', ISO3: 'POL', ISO2: 'PL'}; break;
    case 'portugal' : return { IOC: 'POR', FIFA: 'POR', ISO3: 'PRT', ISO2: 'PT'}; break;
    case 'puerto rico' : return { IOC: 'PUR', FIFA: 'PUR', ISO3: 'PRI', ISO2: 'PR'}; break;
    case 'qatar' : return { IOC: 'QAT', FIFA: 'QAT', ISO3: 'QAT', ISO2: 'QA'}; break;
    case 'romania' : return { IOC: 'ROU', FIFA: 'ROU', ISO3: 'ROU', ISO2: 'RO'}; break;
    case 'russia' : return { IOC: 'RUS', FIFA: 'RUS', ISO3: 'RUS', ISO2: 'RU'}; break;
    case 'rwanda' : return { IOC: 'RWA', FIFA: 'RWA', ISO3: 'RWA', ISO2: 'RW'}; break;
    case 'saint kitts and nevis' : return { IOC: 'SKN', FIFA: 'SKN', ISO3: 'KNA', ISO2: 'KN'}; break;
    case 'saint lucia' : return { IOC: 'LCA', FIFA: 'LCA', ISO3: 'LCA', ISO2: 'LC'}; break;
    case 'saint vincent and the grenadines' : return { IOC: 'VIN', FIFA: 'VIN', ISO3: 'VCT', ISO2: 'VC'}; break;
    case 'samoa' : return { IOC: 'SAM', FIFA: 'SAM', ISO3: 'WSM', ISO2: 'WS'}; break;
    case 'san marino' : return { IOC: 'SMR', FIFA: 'SMR', ISO3: 'SMR', ISO2: 'SM'}; break;
    case 'são tomé and príncipe' : return { IOC: 'STP', FIFA: 'STP', ISO3: 'STP', ISO2: 'ST'}; break;
    case 'saudi arabia' : return { IOC: 'KSA', FIFA: 'KSA', ISO3: 'SAU', ISO2: 'SA'}; break;
    case 'senegal' : return { IOC: 'SEN', FIFA: 'SEN', ISO3: 'SEN', ISO2: 'SN'}; break;
    case 'serbia' : return { IOC: 'SRB', FIFA: 'SRB', ISO3: 'SRB', ISO2: 'RS'}; break;
    case 'seychelles' : return { IOC: 'SEY', FIFA: 'SEY', ISO3: 'SYC', ISO2: 'SC'}; break;
    case 'sierra leone' : return { IOC: 'SLE', FIFA: 'SLE', ISO3: 'SLE', ISO2: 'SL'}; break;
    case 'singapore' : return { IOC: 'SGP', FIFA: 'SIN', ISO3: 'SGP', ISO2: 'SG'}; break;
    case 'slovakia' : return { IOC: 'SVK', FIFA: 'SVK', ISO3: 'SVK', ISO2: 'SK'}; break;
    case 'slovenia' : return { IOC: 'SLO', FIFA: 'SVN', ISO3: 'SVN', ISO2: 'SI'}; break;
    case 'solomon islands' : return { IOC: 'SOL', FIFA: 'SOL', ISO3: 'SLB', ISO2: 'SB'}; break;
    case 'somalia' : return { IOC: 'SOM', FIFA: 'SOM', ISO3: 'SOM', ISO2: 'SO'}; break;
    case 'south africa' : return { IOC: 'RSA', FIFA: 'RSA', ISO3: 'ZAF', ISO2: 'ZA'}; break;
    case 'spain' : return { IOC: 'ESP', FIFA: 'ESP', ISO3: 'ESP', ISO2: 'ES'}; break;
    case 'sri lanka' : return { IOC: 'SRI', FIFA: 'SRI', ISO3: 'LKA', ISO2: 'LK'}; break;
    case 'sudan' : return { IOC: 'SUD', FIFA: 'SDN', ISO3: 'SDN', ISO2: 'SD'}; break;
    case 'suriname' : return { IOC: 'SUR', FIFA: 'SUR', ISO3: 'SUR', ISO2: 'SR'}; break;
    case 'eswatini' : return { IOC: 'SWZ', FIFA: 'SWZ', ISO3: 'SWZ', ISO2: 'SZ'}; break;
    case 'sweden' : return { IOC: 'SWE', FIFA: 'SWE', ISO3: 'SWE', ISO2: 'SE'}; break;
    case 'switzerland' : return { IOC: 'SUI', FIFA: 'SUI', ISO3: 'CHE', ISO2: 'CH'}; break;
    case 'syria' : return { IOC: 'SYR', FIFA: 'SYR', ISO3: 'SYR', ISO2: 'SY'}; break;
    case 'taiwan' : return { IOC: 'TPE', FIFA: 'TPE', ISO3: 'TWN', ISO2: 'TW'}; break;
    case 'tajikistan' : return { IOC: 'TJK', FIFA: 'TJK', ISO3: 'TJK', ISO2: 'TJ'}; break;
    case 'tanzania' : return { IOC: 'TAN', FIFA: 'TAN', ISO3: 'TZA', ISO2: 'TZ'}; break;
    case 'thailand' : return { IOC: 'THA', FIFA: 'THA', ISO3: 'THA', ISO2: 'TH'}; break;
    case 'timor-leste' : return { IOC: 'TLS', FIFA: 'TLS', ISO3: 'TLS', ISO2: 'TL'}; break;
    case 'togo' : return { IOC: 'TOG', FIFA: 'TOG', ISO3: 'TGO', ISO2: 'TG'}; break;
    case 'tonga' : return { IOC: 'TGA', FIFA: 'TGA', ISO3: 'TON', ISO2: 'TO'}; break;
    case 'trinidad and tobago' : return { IOC: 'TTO', FIFA: 'TRI', ISO3: 'TTO', ISO2: 'TT'}; break;
    case 'tunisia' : return { IOC: 'TUN', FIFA: 'TUN', ISO3: 'TUN', ISO2: 'TN'}; break;
    case 'turkey' : return { IOC: 'TUR', FIFA: 'TUR', ISO3: 'TUR', ISO2: 'TR'}; break;
    case 'turkmenistan' : return { IOC: 'TKM', FIFA: 'TKM', ISO3: 'TKM', ISO2: 'TM'}; break;
    case 'turks and caicos islands' : return { IOC: 'TCA', FIFA: 'TCA', ISO3: 'TCA', ISO2: 'TC'}; break;
    case 'uganda' : return { IOC: 'UGA', FIFA: 'UGA', ISO3: 'UGA', ISO2: 'UG'}; break;
    case 'ukraine' : return { IOC: 'UKR', FIFA: 'UKR', ISO3: 'UKR', ISO2: 'UA'}; break;
    case 'united arab emirates' : return { IOC: 'UAE', FIFA: 'UAE', ISO3: 'ARE', ISO2: 'AE'}; break;
    case 'united states' : return { IOC: 'USA', FIFA: 'USA', ISO3: 'USA', ISO2: 'US'}; break;
    case 'united states virgin islands' : return { IOC: 'ISV', FIFA: 'VIR', ISO3: 'VIR', ISO2: 'VI'}; break;
    case 'uruguay' : return { IOC: 'URU', FIFA: 'URU', ISO3: 'URY', ISO2: 'UY'}; break;
    case 'uzbekistan' : return { IOC: 'UZB', FIFA: 'UZB', ISO3: 'UZB', ISO2: 'UZ'}; break;
    case 'vanuatu' : return { IOC: 'VAN', FIFA: 'VAN', ISO3: 'VUT', ISO2: 'VU'}; break;
    case 'venezuela' : return { IOC: 'VEN', FIFA: 'VEN', ISO3: 'VEN', ISO2: 'VE'}; break;
    case 'vietnam' : return { IOC: 'VIE', FIFA: 'VIE', ISO3: 'VNM', ISO2: 'VN'}; break;
    case 'yemen' : return { IOC: 'YEM', FIFA: 'YEM', ISO3: 'YEM', ISO2: 'YE'}; break;
    case 'zambia' : return { IOC: 'ZAM', FIFA: 'ZAM', ISO3: 'ZMB', ISO2: 'ZM'}; break;
    case 'zimbabwe' : return { IOC: 'ZIM', FIFA: 'ZIM', ISO3: 'ZWE', ISO2: 'ZW'}; break;
    case 'united kingdom' : return { IOC: 'GBR', FIFA: 'GBR', ISO3: 'GBR', ISO2: 'GB'}; break;
    default: return "Country not found"; break;
  }

}